/**
 * Cultures du scénario Monde 1400. Regroupements volontairement larges :
 * une « culture » de jeu désigne un ensemble linguistique et politique
 * reconnaissable vers 1400, pas une identité figée. Les listes de noms sont
 * des prénoms et noms de lignées attestés ou courants dans ces sociétés.
 */
import type { CultureDef, ModifierMap, SuccessionLaw, UnitType } from '@ttc/shared';

type Clothing = 'imperial' | 'chivalric' | 'northern' | 'southern' | 'eastern' | 'moorland' | 'maritime' | 'steppe' | 'robed' | 'tropical' | 'andean' | 'plains' | 'islander' | 'silk';

interface Spec {
  id: string;
  name: string;
  group: string;
  color: string;
  region: string;
  law: SuccessionLaw;
  skin: number[];
  hair: number[];
  clothing: Clothing;
  m: string;
  f: string;
  h: string;
  mods?: ModifierMap;
  unit?: UnitType;
}

const CULTURE_NAMES: Record<string, { name: string; group: string }> = {};

function c(s: Spec): CultureDef {
  CULTURE_NAMES[s.id] = { name: s.name, group: s.group };
  const split = (x: string) => x.split(',').map((v) => v.trim()).filter(Boolean);
  const houses = split(s.h);
  return {
    id: s.id,
    color: s.color,
    region: s.region,
    maleNames: split(s.m),
    femaleNames: split(s.f),
    houseNames: houses,
    placeSyllables: { start: houses.map((h) => h.slice(0, 3)), mid: ['a', 'e', 'i', 'o', ''], end: ['a', 'an', 'ia', 'or', 'um'] },
    modifiers: s.mods ?? {},
    favoredUnit: s.unit,
    appearance: { skinTones: s.skin, hairColors: s.hair, clothing: s.clothing },
    succession: s.law,
  };
}

export const CULTURES_1400: CultureDef[] = [
  // --- Europe latine et germanique -----------------------------------------
  c({ id: 'french', name: 'Français', group: 'latin', color: '#3f5fa8', region: 'France', law: 'primogeniture', skin: [0, 1, 2], hair: [1, 2, 3, 0], clothing: 'chivalric', unit: 'heavy_cavalry', m: 'Charles, Louis, Jean, Philippe, Pierre, Guillaume, Robert, Hugues, Bertrand, Enguerrand, Olivier, Arnaud, Raoul, Thibaut', f: 'Isabeau, Jeanne, Marguerite, Blanche, Catherine, Marie, Agnès, Béatrice, Yolande, Isabelle', h: 'Valois, Bourbon, Harcourt, Coucy, Montmorency, Craon, Chalon, Vergy, Luxembourg, Armagnac, Foix, Albret' }),
  c({ id: 'occitan', name: 'Occitans', group: 'latin', color: '#b3573a', region: 'Midi', law: 'partition', skin: [1, 2], hair: [2, 3, 4], clothing: 'chivalric', m: 'Bernat, Ramon, Guilhem, Peire, Arnaut, Jordan, Gaston, Bertran, Amanieu, Sicard', f: 'Esclarmonda, Azalais, Ermengarda, Na Maria, Condor, Guillelma, Alazais', h: 'Foix, Armagnac, Comminges, Lautrec, Lévis, Narbonne, Polignac, Uzès' }),
  c({ id: 'breton', name: 'Bretons', group: 'celtic', color: '#2c4c6c', region: 'Bretagne', law: 'primogeniture', skin: [0, 1], hair: [1, 2, 3, 5], clothing: 'chivalric', m: 'Jean, Artur, Alain, Olivier, Tanguy, Guy, Hervé, Even, Pierre, Rolland', f: 'Jeanne, Marguerite, Anne, Aliénor, Isabeau, Tiphaine', h: 'Montfort, Rohan, Laval, Rieux, Clisson, Penthièvre, Tournemine' }),
  c({ id: 'english', name: 'Anglais', group: 'germanic', color: '#b82e36', region: 'Angleterre', law: 'primogeniture', skin: [0, 1], hair: [0, 1, 2, 5], clothing: 'chivalric', unit: 'archers', m: 'Henry, Thomas, Richard, John, Edward, William, Humphrey, Ralph, Walter, Robert, Edmund, Roger', f: 'Joan, Margaret, Philippa, Eleanor, Anne, Isabel, Katherine, Alice, Elizabeth, Blanche', h: 'Lancaster, York, Beaufort, Percy, Neville, Mowbray, Holland, Mortimer, Stafford, Courtenay, Fitzalan' }),
  c({ id: 'scottish', name: 'Écossais', group: 'celtic', color: '#3a5c86', region: 'Écosse', law: 'primogeniture', skin: [0, 1], hair: [0, 1, 5, 2], clothing: 'moorland', m: 'Robert, James, David, Alexander, Archibald, Walter, John, Patrick, William, Duncan', f: 'Annabella, Margaret, Isabella, Euphemia, Mary, Marjorie, Egidia', h: 'Stewart, Douglas, Dunbar, Lindsay, Campbell, Drummond, Hay, Keith' }),
  c({ id: 'gaelic', name: 'Gaëls', group: 'celtic', color: '#3f8a52', region: 'Irlande et Hautes-Terres', law: 'elective', skin: [0, 1], hair: [5, 1, 2, 0], clothing: 'moorland', m: 'Art, Niall, Domhnall, Brian, Toirdhealbhach, Tadhg, Conchobhar, Aodh, Eoghan, Diarmait', f: 'Gormlaith, Sadhbh, Mór, Nuala, Fionnuala, Siobhán, Una', h: 'Ó Néill, Mac Murchadha, Ó Briain, Ó Domhnaill, Mac Carthaigh, Ó Conchobhair, MacDomhnaill' }),
  c({ id: 'welsh', name: 'Gallois', group: 'celtic', color: '#9a3a2f', region: 'Pays de Galles', law: 'partition', skin: [0, 1], hair: [2, 3, 5], clothing: 'moorland', m: 'Owain, Gruffudd, Rhys, Llywelyn, Maredudd, Tudur, Dafydd, Hywel, Ieuan', f: 'Gwenllian, Angharad, Nest, Margred, Catrin, Efa', h: 'Glyndŵr, Tudur, ap Gruffudd, Herbert, Dinefwr, Mathrafal' }),
  c({ id: 'dutch', name: 'Néerlandais et Flamands', group: 'germanic', color: '#d38b2e', region: 'Pays-Bas', law: 'primogeniture', skin: [0, 1], hair: [0, 1, 2], clothing: 'chivalric', mods: { tax_mult: 0.05 }, m: 'Willem, Jan, Albrecht, Floris, Dirk, Arnoud, Gerard, Jacob, Hendrik, Reinoud', f: 'Jacoba, Margaretha, Aleid, Machteld, Beatrijs, Johanna, Katharina', h: 'Wittelsbach, Egmond, Arkel, Brederode, Van der Lek, Wassenaar, Gruuthuse' }),
  c({ id: 'german', name: 'Allemands', group: 'germanic', color: '#5c5c5c', region: 'Saint-Empire', law: 'partition', skin: [0, 1], hair: [0, 1, 2, 3], clothing: 'chivalric', unit: 'heavy_cavalry', m: 'Ruprecht, Friedrich, Heinrich, Albrecht, Ludwig, Wilhelm, Johann, Konrad, Otto, Rudolf, Eberhard, Ernst, Wenzel, Sigismund', f: 'Elisabeth, Margarete, Anna, Katharina, Agnes, Mechthild, Adelheid, Sophie, Beatrix', h: 'Wittelsbach, Habsburg, Wettin, Hohenzollern, Welf, Württemberg, Nassau, Hessen, Askanien, Zähringen, Görz, Cilli' }),
  c({ id: 'swiss', name: 'Confédérés', group: 'germanic', color: '#a33f3f', region: 'Confédération', law: 'elective', skin: [0, 1], hair: [1, 2, 3], clothing: 'chivalric', unit: 'pikemen', m: 'Hans, Rudolf, Ulrich, Werner, Heinrich, Konrad, Peter, Walter, Jost', f: 'Anna, Verena, Elsbeth, Margaretha, Ita', h: 'Attinghausen, Reding, Bubenberg, Stüssi, Manesse, Brun' }),
  c({ id: 'italian', name: 'Italiens', group: 'latin', color: '#3d8c6e', region: 'Italie', law: 'partition', skin: [1, 2, 3], hair: [2, 3, 4], clothing: 'southern', mods: { tax_mult: 0.08 }, m: 'Gian Galeazzo, Francesco, Giovanni, Antonio, Niccolò, Ludovico, Carlo, Pietro, Alberto, Guglielmo, Filippo, Ladislao, Bonifacio, Tommaso', f: 'Caterina, Beatrice, Giovanna, Bianca, Margherita, Lucrezia, Isabella, Costanza, Agnese', h: 'Visconti, Este, Gonzaga, Carrara, Medici, Albizzi, Malatesta, Montefeltro, Scaligeri, Colonna, Orsini, Savoia, Doria, Grimaldi' }),
  c({ id: 'castilian', name: 'Castillans', group: 'latin', color: '#c9a232', region: 'Castille', law: 'primogeniture', skin: [1, 2, 3], hair: [2, 3, 4], clothing: 'southern', m: 'Enrique, Juan, Fernando, Alfonso, Pedro, Diego, Álvaro, Ruy, Gonzalo, Íñigo, Lope, Pero', f: 'Catalina, Leonor, Juana, María, Isabel, Beatriz, Constanza, Urraca, Teresa', h: 'Trastámara, Mendoza, Guzmán, Enríquez, Manrique, Velasco, Stúñiga, Pimentel, Luna, Ayala' }),
  c({ id: 'catalan', name: 'Catalans et Aragonais', group: 'latin', color: '#d4a640', region: 'Couronne d’Aragon', law: 'primogeniture', skin: [1, 2], hair: [2, 3, 4], clothing: 'southern', mods: { tax_mult: 0.05 }, m: 'Martí, Pere, Joan, Jaume, Alfons, Ferran, Bernat, Ramon, Berenguer, Guillem', f: 'Violant, Elionor, Maria, Sibil·la, Margarida, Isabel, Constança', h: 'Barcelona, Urgell, Cardona, Montcada, Luna, Centelles, Pallars, Rocabertí' }),
  c({ id: 'portuguese', name: 'Portugais', group: 'latin', color: '#4c8a3b', region: 'Portugal', law: 'primogeniture', skin: [1, 2, 3], hair: [2, 3, 4], clothing: 'southern', m: 'João, Duarte, Pedro, Henrique, Afonso, Fernando, Nuno, Álvaro, Gonçalo, Rui', f: 'Filipa, Isabel, Beatriz, Leonor, Branca, Teresa, Inês', h: 'Avis, Pereira, Meneses, Coutinho, Castro, Cunha, Silva, Sousa' }),
  c({ id: 'basque', name: 'Navarrais et Basques', group: 'latin', color: '#7b3a4c', region: 'Navarre', law: 'primogeniture', skin: [1, 2], hair: [2, 3, 4], clothing: 'southern', m: 'Carlos, Juan, Godofre, Luis, Pedro, Lanzarote, Martín, Beltrán', f: 'Leonor, Blanca, Juana, Isabel, María, Beatriz', h: 'Évreux, Peralta, Beaumont, Navarra, Agramont, Luxa' }),
  c({ id: 'sardinian', name: 'Sardes', group: 'latin', color: '#8a6d3b', region: 'Sardaigne', law: 'primogeniture', skin: [2, 3], hair: [3, 4], clothing: 'southern', m: 'Mariano, Brancaleone, Ugone, Guglielmo, Barisone, Comita', f: 'Eleonora, Benedetta, Elena, Preziosa', h: 'Arborea, Doria, Bas-Serra, Lacon, Gunale' }),

  // --- Europe du Nord et de l'Est -------------------------------------------
  c({ id: 'danish', name: 'Danois', group: 'norse', color: '#b33b3b', region: 'Danemark', law: 'elective', skin: [0], hair: [0, 1, 5], clothing: 'northern', m: 'Erik, Christoffer, Valdemar, Olaf, Knud, Niels, Henning, Anders, Peder', f: 'Margrete, Ingeborg, Kristina, Filippa, Helvig, Cecilie', h: 'Estridsen, Pommern, Podebusk, Brahe, Krognos, Rosenkrantz, Thott' }),
  c({ id: 'norwegian', name: 'Norvégiens', group: 'norse', color: '#8d4a4a', region: 'Norvège', law: 'primogeniture', skin: [0], hair: [0, 1, 5], clothing: 'northern', m: 'Håkon, Olav, Magnus, Sigurd, Eirik, Sverre, Alv, Ogmund, Jon', f: 'Ingebjørg, Margrete, Ragnhild, Sigrid, Kristin, Gyrid', h: 'Sverre, Sudreim, Giske, Aspa, Bolt, Rømer' }),
  c({ id: 'swedish', name: 'Suédois', group: 'norse', color: '#3c6fb0', region: 'Suède', law: 'elective', skin: [0], hair: [0, 1, 5], clothing: 'northern', m: 'Albrekt, Bo, Karl, Magnus, Knut, Sten, Bengt, Erengisle, Nils, Birger', f: 'Birgitta, Katarina, Märta, Ingrid, Kristina, Cecilia', h: 'Jonsson, Bonde, Sparre, Natt och Dag, Bielke, Oxenstierna, Folkunga' }),
  c({ id: 'icelandic', name: 'Islandais', group: 'norse', color: '#7a8fa0', region: 'Islande', law: 'elective', skin: [0], hair: [0, 1, 5], clothing: 'northern', m: 'Björn, Jón, Þorsteinn, Ari, Gizur, Sturla, Einar, Snorri', f: 'Ólöf, Guðrún, Þórdís, Helga, Ragnheiður', h: 'Sturlungar, Haukdælir, Oddaverjar, Svalbarðs' }),
  c({ id: 'finnic', name: 'Finnois et Estes', group: 'uralic', color: '#6f9aa6', region: 'Finlande et Estonie', law: 'elective', skin: [0], hair: [0, 1], clothing: 'northern', m: 'Ukko, Tuomas, Heikki, Lauri, Olli, Matti, Paavo, Kalev', f: 'Aino, Kaisa, Marketta, Elina, Ilma', h: 'Kurki, Tavast, Horn, Fleming, Stålarm' }),
  c({ id: 'sami', name: 'Samis', group: 'uralic', color: '#9fb7a6', region: 'Sápmi', law: 'elective', skin: [0, 1], hair: [2, 3], clothing: 'northern', m: 'Ámmon, Niillas, Ánte, Jovnna, Biret-Ánte, Máhtte', f: 'Biret, Máret, Elle, Inger, Risten', h: 'Siida du Nord, Siida des lacs, Siida des fjords, Siida de la toundra' }),
  c({ id: 'polish', name: 'Polonais', group: 'slavic', color: '#c24a4a', region: 'Pologne', law: 'elective', skin: [0, 1], hair: [0, 1, 2, 3], clothing: 'eastern', unit: 'heavy_cavalry', m: 'Władysław, Kazimierz, Bolesław, Siemowit, Janusz, Zbigniew, Spytek, Jan, Mikołaj, Piotr', f: 'Jadwiga, Anna, Elżbieta, Zofia, Katarzyna, Małgorzata, Aleksandra', h: 'Piast, Jagiellon, Tęczyński, Oleśnicki, Topór, Leliwa, Pilecki, Odrowąż' }),
  c({ id: 'lithuanian', name: 'Lituaniens', group: 'baltic', color: '#7a8a3a', region: 'Lituanie', law: 'seniority', skin: [0, 1], hair: [0, 1, 2], clothing: 'eastern', unit: 'light_cavalry', m: 'Vytautas, Jogaila, Švitrigaila, Kęstutis, Algirdas, Žygimantas, Skirgaila, Kaributas, Vaidotas', f: 'Ona, Birutė, Aldona, Rimgailė, Danutė, Sofija', h: 'Gediminaičiai, Goštautai, Radvilos, Olelkaičiai, Kęsgailos' }),
  c({ id: 'baltic', name: 'Baltes (Samogitiens, Coures, Lettons)', group: 'baltic', color: '#8fa24a', region: 'Baltique orientale', law: 'elective', skin: [0], hair: [0, 1], clothing: 'northern', m: 'Kintautas, Rumbaudas, Vilkas, Mantas, Butegeidis, Namejs, Lamekins', f: 'Gaile, Milda, Rasa, Austra, Laima', h: 'Kęsgaila, Butrimas, Vaišvilkas, Namejs' }),
  c({ id: 'czech', name: 'Tchèques', group: 'slavic', color: '#8a5ca8', region: 'Bohême', law: 'primogeniture', skin: [0, 1], hair: [0, 1, 2, 3], clothing: 'chivalric', m: 'Václav, Jan, Jindřich, Oldřich, Boček, Petr, Jošt, Prokop, Zikmund', f: 'Žofie, Kateřina, Anna, Eliška, Markéta', h: 'Lucemburk, Rožmberk, Šternberk, Lichtenburk, Hazmburk, Kunštát' }),
  c({ id: 'hungarian', name: 'Hongrois', group: 'finno_ugric', color: '#4d8a5a', region: 'Hongrie', law: 'primogeniture', skin: [0, 1, 2], hair: [1, 2, 3], clothing: 'eastern', unit: 'light_cavalry', m: 'Zsigmond, Miklós, János, László, István, Pál, Imre, Lőrinc, Hermann, Péter', f: 'Mária, Borbála, Erzsébet, Katalin, Ilona, Anna', h: 'Garai, Kanizsai, Cillei, Hunyadi, Bebek, Lackfi, Rozgonyi, Szapolyai' }),
  c({ id: 'croatian', name: 'Croates', group: 'south_slavic', color: '#5673a8', region: 'Croatie', law: 'partition', skin: [0, 1], hair: [1, 2, 3], clothing: 'eastern', m: 'Hrvoje, Ivaniš, Nikola, Stjepan, Pavao, Juraj, Frankopan', f: 'Katarina, Jelena, Doroteja, Margarita', h: 'Frankopan, Šubić, Horvat, Nelipić, Kurjaković, Talovac' }),
  c({ id: 'serbian', name: 'Serbes et Bosniens', group: 'south_slavic', color: '#a8433b', region: 'Balkans occidentaux', law: 'partition', skin: [0, 1, 2], hair: [2, 3, 4], clothing: 'eastern', m: 'Stefan, Đurađ, Vuk, Lazar, Tvrtko, Ostoja, Hrvoje, Sandalj, Balša, Radič, Mihailo', f: 'Milica, Jelena, Mara, Katarina, Olivera, Jelisaveta', h: 'Lazarević, Branković, Kotromanić, Hranić, Balšić, Kosača, Crnojević, Pavlović' }),
  c({ id: 'bulgarian', name: 'Bulgares', group: 'south_slavic', color: '#6a8a3a', region: 'Bulgarie', law: 'partition', skin: [1, 2], hair: [2, 3, 4], clothing: 'eastern', m: 'Konstantin, Ivan, Fruzhin, Aleksandar, Shishman, Mihail, Asen', f: 'Kera Tamara, Keratsa, Anna, Irina, Desislava', h: 'Shishman, Sratsimir, Asen, Terter, Smilets' }),
  c({ id: 'romanian', name: 'Valaques et Moldaves', group: 'latin', color: '#c9a03a', region: 'Valachie et Moldavie', law: 'elective', skin: [1, 2], hair: [2, 3, 4], clothing: 'eastern', m: 'Mircea, Vlad, Mihail, Dan, Alexandru, Iuga, Ștefan, Petru, Radu, Basarab', f: 'Mara, Ana, Margareta, Ecaterina, Ruxandra, Maria', h: 'Basarab, Mușat, Drăculești, Dănești, Bogdănești' }),
  c({ id: 'albanian', name: 'Albanais', group: 'balkan', color: '#b33a3a', region: 'Albanie', law: 'partition', skin: [1, 2], hair: [2, 3, 4], clothing: 'eastern', m: 'Gjergj, Gjon, Karl, Pal, Lekë, Andrea, Tanush, Nikollë', f: 'Mara, Voisava, Angjelina, Donika, Kristina', h: 'Kastrioti, Topia, Dukagjini, Arianiti, Muzaka, Balsha, Zaharia' }),
  c({ id: 'greek', name: 'Grecs (Romaioi)', group: 'hellenic', color: '#6a3a8c', region: 'Romanie', law: 'primogeniture', skin: [1, 2, 3], hair: [2, 3, 4], clothing: 'imperial', mods: { monthly_prestige: 0.1 }, m: 'Manuel, Ioannes, Theodoros, Andronikos, Konstantinos, Demetrios, Michael, Alexios, Thomas, Nikephoros', f: 'Helene, Anna, Maria, Eirene, Theodora, Zoe, Sophia, Eudokia', h: 'Palaiologos, Kantakouzenos, Laskaris, Notaras, Doukas, Komnenos, Asanes, Philanthropenos' }),
  c({ id: 'ruthenian', name: 'Ruthènes', group: 'east_slavic', color: '#7c8a4a', region: 'Ruthénie', law: 'seniority', skin: [0, 1], hair: [1, 2, 3], clothing: 'eastern', m: 'Volodymyr, Fedir, Semen, Andriy, Dmytro, Ivan, Yuriy, Mykhailo, Oleksandr', f: 'Olena, Anna, Mariya, Yevdokiya, Ulyana, Solomiya', h: 'Olelkovychi, Ostrozki, Chortoryiski, Zbarazki, Holshanski, Koriatovychi' }),
  c({ id: 'russian', name: 'Russes', group: 'east_slavic', color: '#4f7a3a', region: 'Rus’', law: 'seniority', skin: [0, 1], hair: [1, 2, 3], clothing: 'eastern', m: 'Vasily, Dmitry, Ivan, Yury, Mikhail, Andrei, Boris, Semyon, Konstantin, Oleg, Fyodor, Daniil', f: 'Sofia, Evdokia, Anna, Maria, Anastasia, Elena, Ulyana', h: 'Riourikides de Moscou, de Tver, de Riazan, de Souzdal, de Rostov, de Iaroslavl, Vsevolozhsky, Shuysky' }),
  c({ id: 'novgorodian', name: 'Novgorodiens', group: 'east_slavic', color: '#5d8a7a', region: 'Novgorod', law: 'elective', skin: [0, 1], hair: [0, 1, 2], clothing: 'eastern', mods: { tax_mult: 0.08 }, m: 'Timofey, Yury, Vasily, Ivan, Grigory, Ontsifor, Afanasy, Isaak', f: 'Marfa, Nastasya, Evfimiya, Anna', h: 'Mishinichi, Borecki, Ovinov, Esipov, Nesterov' }),

  // --- Monde islamique, Proche-Orient, Caucase -------------------------------
  c({ id: 'turkish', name: 'Turcs d’Anatolie', group: 'oghuz', color: '#4f9a6a', region: 'Anatolie', law: 'seniority', skin: [1, 2, 3], hair: [3, 4, 6], clothing: 'southern', unit: 'light_cavalry', m: 'Bayezid, Süleyman, Mehmed, Musa, İsa, Murad, Mustafa, Orhan, Alaeddin, İsfendiyar, İbrahim, Cüneyd', f: 'Devlet Hatun, Hafsa, Selçuk, Nilüfer, Mâhperi, Hatice', h: 'Osmanoğlu, Karamanoğlu, Candaroğlu, Germiyanoğlu, Aydınoğlu, Menteşeoğlu, Dulkadiroğlu, Ramazanoğlu' }),
  c({ id: 'turkmen', name: 'Turkmènes', group: 'oghuz', color: '#7a9a4a', region: 'Djézireh et Azerbaïdjan', law: 'seniority', skin: [1, 2, 3], hair: [3, 4, 6], clothing: 'steppe', unit: 'horse_archers', m: 'Qara Yusuf, Qara Osman, Pir Ali, İskender, Qutlu, Ahmed, Hamza, Jahan Shah', f: 'Sara, Seljuk Shah, Tatar Khatun, Arghun', h: 'Aq Qoyunlu, Qara Qoyunlu, Bayandur, Baharlu, Dulkadir' }),
  c({ id: 'arab_levant', name: 'Arabes du Levant et d’Égypte', group: 'arab', color: '#c8a44a', region: 'Égypte et Syrie', law: 'elective', skin: [2, 3, 4], hair: [3, 4, 6], clothing: 'southern', mods: { tax_mult: 0.05 }, m: 'Faraj, Barquq, Shaykh, Tatar, Jaqmaq, Yashbak, Tanibak, Nawruz, Qalawun, Muhammad, Ahmad, Ali', f: 'Khawand, Fatima, Zaynab, Khadija, Shirin, Aisha', h: 'Barquqiyya, Zahiriyya, Qalawunides, Mahmudiyya, Mu’ayyadiyya' }),
  c({ id: 'arab_bedouin', name: 'Arabes de la péninsule', group: 'arab', color: '#d9b35a', region: 'Arabie', law: 'elective', skin: [2, 3, 4], hair: [4, 6], clothing: 'southern', unit: 'light_cavalry', m: 'Hasan, Ajlan, Rumaytha, Barakat, Ahmad, Muhammad, Mani, Jabr, Zamil, Abd Allah', f: 'Fatima, Nura, Hind, Salma, Aisha', h: 'Hashimites, Rasulides, Tahirides, Banu Jabr, Usfurides, Al Muhanna' }),
  c({ id: 'arab_iraqi', name: 'Arabes d’Irak', group: 'arab', color: '#b58c3a', region: 'Irak', law: 'elective', skin: [2, 3], hair: [3, 4, 6], clothing: 'southern', m: 'Ahmad, Uways, Husayn, Ali, Hasan, Jalal, Sultan', f: 'Tandu, Fatima, Dilshad, Zaynab', h: 'Jalayirides, Musha’sha’, Banu Asad, Muntafiq' }),
  c({ id: 'maghrebi', name: 'Arabes du Maghreb', group: 'arab', color: '#b87a3a', region: 'Maghreb', law: 'elective', skin: [2, 3, 4], hair: [3, 4, 6], clothing: 'southern', m: 'Abu Said, Abu Faris, Abu Hammu, Abu Zayyan, Uthman, Abd al-Aziz, Abu Tashufin, Muhammad, Abu Bakr', f: 'Aisha, Fatima, Zaynab, Umm al-Hasan, Khadija', h: 'Mérinides, Hafsides, Zianides, Wattassides, Banu Hilal' }),
  c({ id: 'andalusi', name: 'Andalous', group: 'arab', color: '#2f8a6a', region: 'Grenade', law: 'elective', skin: [1, 2, 3], hair: [3, 4], clothing: 'southern', mods: { tax_mult: 0.06 }, m: 'Muhammad, Yusuf, Ismail, Nasr, Sa’d, Ali, Abu l-Hasan', f: 'Aisha, Fatima, Zoraya, Maryam', h: 'Nasrides, Banu Sarraj, Banu Ashqilula, Banu Mufarrij' }),
  c({ id: 'berber', name: 'Amazighs', group: 'berber', color: '#a86a3a', region: 'Atlas et Sahara', law: 'elective', skin: [2, 3, 4], hair: [3, 4, 6], clothing: 'southern', unit: 'light_cavalry', m: 'Yusuf, Tashfin, Yaghmurasan, Amghar, Ziri, Idir, Tamim, Mennad', f: 'Tin Hinan, Kahina, Tiziri, Thiziri, Dassin', h: 'Aït Hintata, Aït Atta, Banu Marin, Kel Ajjer, Sanhaja' }),
  c({ id: 'tuareg', name: 'Touaregs', group: 'berber', color: '#5a7ab0', region: 'Sahara central', law: 'elective', skin: [3, 4, 5], hair: [4, 6], clothing: 'robed', unit: 'light_cavalry', m: 'Akil, Ag Amastan, Moussa, Ilias, Eghless, Ag Ahmed', f: 'Dassine, Tin Hinan, Fadimata, Tadjit', h: 'Kel Ahaggar, Kel Aïr, Kel Adrar, Kel Ajjer, Iwellemmeden' }),
  c({ id: 'nubian', name: 'Nubiens', group: 'nilo_saharan', color: '#8a4a2a', region: 'Nubie', law: 'elective', skin: [5, 6, 7], hair: [4, 6], clothing: 'robed', m: 'Joel, Siti, Kudanbes, Abdallah, Kerenbes, Eltedda', f: 'Martha, Mariam, Kyra, Kandake', h: 'Maison de Dotawo, Banu Kanz, Funj anciens, Maison de Kasr Ibrim' }),
  c({ id: 'kurdish', name: 'Kurdes', group: 'iranian', color: '#8a6a4a', region: 'Kurdistan', law: 'partition', skin: [1, 2, 3], hair: [3, 4], clothing: 'southern', m: 'Izz al-Din, Sharaf, Badr, Mir Hasan, Shams al-Din, Muhammad', f: 'Khanzade, Zarifa, Shirin, Gulizar', h: 'Bohtan, Hakkari, Ardalan, Bitlis, Soran, Hasankeyf (Ayyoubides)' }),
  c({ id: 'persian', name: 'Persans', group: 'iranian', color: '#3a8a8a', region: 'Iran', law: 'partition', skin: [1, 2, 3], hair: [3, 4, 6], clothing: 'southern', mods: { monthly_prestige: 0.05 }, m: 'Iskandar, Pir Muhammad, Ibrahim, Mansur, Shah Shuja, Ahmad, Hasan, Ali, Ismail, Husayn', f: 'Gawharshad, Tandu, Sara, Khanzade, Parizad, Shirin', h: 'Muzaffarides, Kartides, Injuides, Sarbadars, Marashis, Paduspanides, Bavandides' }),
  c({ id: 'afghan', name: 'Pachtounes', group: 'iranian', color: '#8a8a4a', region: 'Afghanistan', law: 'elective', skin: [1, 2, 3], hair: [3, 4, 6], clothing: 'southern', unit: 'light_cavalry', m: 'Bahlul, Sultan Shah, Daud, Khan Jahan, Ahmad, Sher, Ibrahim', f: 'Nazo, Zarghuna, Malala, Bibi', h: 'Lodi, Sur, Niazi, Farmuli, Yusufzai' }),
  c({ id: 'armenian', name: 'Arméniens', group: 'caucasian', color: '#a8433f', region: 'Arménie', law: 'primogeniture', skin: [1, 2], hair: [3, 4], clothing: 'eastern', m: 'Levon, Hethum, Kostandin, Grigor, Smbat, Vasak, Oshin, Sahak', f: 'Zabel, Mariun, Rita, Keran, Fimi', h: 'Orbelian, Proshian, Zakarian, Artsruni, Hasan-Jalalian, Lusignan d’Arménie' }),
  c({ id: 'georgian', name: 'Géorgiens', group: 'caucasian', color: '#b35a5a', region: 'Géorgie', law: 'primogeniture', skin: [1, 2], hair: [3, 4], clothing: 'eastern', m: 'Giorgi, Konstantine, Aleksandre, Bagrat, Vakhtang, Dimitri, Davit, Levan', f: 'Tamar, Rusudan, Nestan-Darejan, Ketevan, Helene', h: 'Bagrationi, Dadiani, Gurieli, Jaqeli, Orbeliani, Amilakhvari' }),
  c({ id: 'circassian', name: 'Circassiens et peuples du Caucase', group: 'caucasian', color: '#6a8a5a', region: 'Caucase du Nord', law: 'elective', skin: [0, 1], hair: [1, 2, 3], clothing: 'steppe', unit: 'light_cavalry', m: 'Inal, Temruk, Kaytuk, Beslan, Aslan, Kabard', f: 'Guasha, Malechipkh, Satanay, Nalmes', h: 'Inalides, Kabarda, Besleney, Shapsug, Avars (khanat)' }),
  c({ id: 'tajik', name: 'Tadjiks et Sogdiens', group: 'iranian', color: '#5a9a8a', region: 'Transoxiane', law: 'partition', skin: [1, 2], hair: [3, 4], clothing: 'southern', mods: { tax_mult: 0.05 }, m: 'Ulugh Beg, Shah Rukh, Ibrahim, Abu Said, Husayn, Ali, Kamal', f: 'Gawharshad, Saray Mulk, Tuman Agha, Bibi Khanum', h: 'Karts, Sayyids de Termez, Khwajas de Samarcande, Naqshbandis' }),
  c({ id: 'chagatai', name: 'Turcs tchaghataïs', group: 'turkic', color: '#9a7a3a', region: 'Transoxiane et Moghulistan', law: 'seniority', skin: [1, 2, 3], hair: [3, 4, 6], clothing: 'steppe', unit: 'horse_archers', m: 'Timur, Shah Rukh, Miran Shah, Umar Shaykh, Pir Muhammad, Khalil Sultan, Khizr Khwaja, Muhammad, Sultan Husayn', f: 'Saray Mulk, Tuman Agha, Chulpan Mulk, Khanzade, Gawharshad', h: 'Timourides, Barlas, Dughlat, Tchaghataïdes, Jalayir, Arlat' }),

  // --- Steppes, Sibérie ------------------------------------------------------
  c({ id: 'kipchak', name: 'Tatars de la Horde', group: 'turkic', color: '#b5903a', region: 'Horde d’Or', law: 'seniority', skin: [1, 2, 3], hair: [3, 4, 6], clothing: 'steppe', unit: 'horse_archers', m: 'Shadi Beg, Edigu, Tokhtamysh, Timur Qutlugh, Pulad, Jalal ad-Din, Kadir Berdi, Ulugh Muhammad, Nur ad-Din', f: 'Taydula, Toghay, Jan Bike, Khanike', h: 'Djötchides, Manghit, Shirin, Barin, Arghin, Qipchaq' }),
  c({ id: 'kazakh', name: 'Nomades de la steppe blanche', group: 'turkic', color: '#c9aa5a', region: 'Steppe kazakhe', law: 'seniority', skin: [1, 2, 3], hair: [3, 4, 6], clothing: 'steppe', unit: 'horse_archers', m: 'Baraq, Urus, Kuyirchak, Abu’l-Khayr, Janibek, Kerei, Sayyid Ahmad', f: 'Aisha, Jan Bike, Kunduz, Aibike', h: 'Chaybanides, Ordaïdes, Toqaïdes, Nogaï, Uak' }),
  c({ id: 'mongol', name: 'Mongols', group: 'mongolic', color: '#8a5a2a', region: 'Mongolie', law: 'seniority', skin: [2, 3], hair: [4, 6], clothing: 'steppe', unit: 'horse_archers', m: 'Elbeg, Gün Temür, Örüg Temür, Öljei Temür, Arughtai, Toghan, Esen, Mahmud, Batula', f: 'Oljei, Samur, Mandukhai, Khutulun, Sechen', h: 'Borjiginides, Khorchin, Ongud, Uriankhai, Taichiud' }),
  c({ id: 'oirat', name: 'Oïrats', group: 'mongolic', color: '#6a7a3a', region: 'Dzoungarie', law: 'elective', skin: [2, 3], hair: [4, 6], clothing: 'steppe', unit: 'horse_archers', m: 'Mahmud, Taiping, Batu-Bolod, Toghon, Esen, Ugechi', f: 'Samur, Kerenghui, Nomin', h: 'Choros, Dörbet, Torghut, Khoshut, Olot' }),
  c({ id: 'uyghur', name: 'Ouïghours', group: 'turkic', color: '#5a8ab0', region: 'Tarim et Tourfan', law: 'seniority', skin: [1, 2, 3], hair: [3, 4, 6], clothing: 'silk', mods: { tax_mult: 0.04 }, m: 'Khizr Khwaja, Muhammad, Sher Muhammad, Ways, Qamar ad-Din, Yunus', f: 'Tokhtamysh Khanum, Aisha, Nurgul', h: 'Dughlat, Tchaghataïdes de l’Est, Idiqut, Khojas de Kachgar' }),
  c({ id: 'tibetan', name: 'Tibétains', group: 'tibetan', color: '#a84a6a', region: 'Tibet', law: 'elective', skin: [2, 3, 4], hair: [4, 6], clothing: 'robed', m: 'Drakpa Gyaltsen, Tsongkhapa, Changchub, Sonam, Tashi, Namkha, Rinchen, Dorje, Palden', f: 'Dolma, Pema, Yangchen, Dechen, Tsering', h: 'Phagmodrupa, Rinpungpa, Sakya, Karmapa, Gongkar, Lhagyari' }),
  c({ id: 'siberian', name: 'Peuples de Sibérie', group: 'siberian', color: '#8aa0a8', region: 'Sibérie', law: 'elective', skin: [1, 2, 3], hair: [4, 6], clothing: 'northern', m: 'Taibuga, Kuchum, Ediger, Bekbulat, Asyka, Tygyn, Ellei, Omogoi', f: 'Sabai, Chokhchoi, Kuonnagan, Ayma', h: 'Taibugides, Chaybanides de Sibérie, clans Khanty, clans Evenks, clans Yakoutes' }),

  // --- Asie du Sud ------------------------------------------------------------
  c({ id: 'hindustani', name: 'Hindoustanis', group: 'indo_aryan', color: '#c26a3a', region: 'Hindoustan', law: 'partition', skin: [2, 3, 4], hair: [4, 6], clothing: 'southern', m: 'Mahmud, Nusrat, Mallu, Khizr, Mubarak, Ibrahim, Sher, Sikandar, Firuz, Ala-ud-Din', f: 'Makhdumah, Razia, Ghazala, Sultana, Laila', h: 'Tughlaq, Sayyid, Sharqi, Lodi, Khalji, Iqbal Khanides' }),
  c({ id: 'rajput', name: 'Rajpoutes', group: 'indo_aryan', color: '#d4843a', region: 'Rajputana', law: 'primogeniture', skin: [2, 3, 4], hair: [4, 6], clothing: 'southern', unit: 'heavy_cavalry', m: 'Lakha, Chunda, Mokal, Rao Chunda, Rinmal, Hammir, Kumbha, Prithviraj, Mansingh, Jodha', f: 'Hansa Bai, Padmini, Kurmadevi, Meera, Karnavati', h: 'Sisodia, Rathore, Chauhan, Kachwaha, Bhati, Tomar, Parmar, Hada' }),
  c({ id: 'gujarati', name: 'Goujaratis', group: 'indo_aryan', color: '#b8a03a', region: 'Goujerat', law: 'partition', skin: [2, 3, 4], hair: [4, 6], clothing: 'southern', mods: { tax_mult: 0.08 }, m: 'Zafar Khan, Tatar Khan, Ahmad, Muhammad, Mahmud, Qutb-ud-Din, Karan', f: 'Bibi Mughali, Rupmati, Sultana', h: 'Muzaffarides, Vaghela, Chudasama, Jhala' }),
  c({ id: 'punjabi', name: 'Pendjabis et Sindhis', group: 'indo_aryan', color: '#a8a04a', region: 'Pendjab et Sind', law: 'partition', skin: [2, 3], hair: [4, 6], clothing: 'southern', m: 'Jasrat, Khizr, Sultan, Jam Tamachi, Jam Salahuddin, Bahadur, Daulat', f: 'Bibi, Sahiba, Heer, Sassui', h: 'Khokhar, Samma, Langah, Bhatti, Janjua' }),
  c({ id: 'kashmiri', name: 'Cachemiris', group: 'indo_aryan', color: '#6a9aa8', region: 'Cachemire', law: 'primogeniture', skin: [1, 2, 3], hair: [3, 4], clothing: 'southern', m: 'Sikandar, Zain-ul-Abidin, Qutb-ud-Din, Shihab-ud-Din, Ali Shah', f: 'Kota Rani, Sura, Lalla', h: 'Shah Mir, Chaks, Magrey, Lolab' }),
  c({ id: 'bengali', name: 'Bengalis', group: 'indo_aryan', color: '#3a9a6a', region: 'Bengale', law: 'partition', skin: [3, 4, 5], hair: [4, 6], clothing: 'southern', mods: { tax_mult: 0.06 }, m: 'Ghiyasuddin Azam, Saifuddin Hamza, Raja Ganesha, Jalaluddin, Shamsuddin, Nasiruddin, Rukunuddin', f: 'Gauri, Rupmati, Lakshmi, Asmani', h: 'Ilyas Shahi, Maison de Ganesha, Habshi, Deva de Bhulua' }),
  c({ id: 'assamese', name: 'Ahoms et peuples d’Assam', group: 'tai', color: '#8a9a3a', region: 'Assam', law: 'primogeniture', skin: [2, 3, 4], hair: [4, 6], clothing: 'tropical', m: 'Sudangphaa, Sujangphaa, Sukhangphaa, Tyao Khamti, Susenphaa', f: 'Nang Mung, Nang Lai, Mula Gabharu', h: 'Ahoms, Chutia, Kamata, Dimasa, Koch' }),
  c({ id: 'oriya', name: 'Odias', group: 'indo_aryan', color: '#b35a8a', region: 'Orissa', law: 'primogeniture', skin: [3, 4, 5], hair: [4, 6], clothing: 'southern', m: 'Narasimha Deva, Bhanu Deva, Kapilendra, Purushottama, Prataparudra', f: 'Padmavati, Rupambika, Chandrika', h: 'Ganga orientaux, Suryavamsa, Bhanja' }),
  c({ id: 'marathi', name: 'Marathes et Deccanis', group: 'indo_aryan', color: '#c9723a', region: 'Deccan', law: 'partition', skin: [3, 4, 5], hair: [4, 6], clothing: 'southern', m: 'Firuz Shah, Ahmad Shah, Tajuddin, Muhammad, Mujahid, Ramachandra, Singhana', f: 'Aga Zainab, Jijabai, Gauri', h: 'Bahmanides, Yadavas (lignée), Faruqi, Gonds de Kherla' }),
  c({ id: 'telugu', name: 'Télougous', group: 'dravidian', color: '#b33a6a', region: 'Andhra', law: 'primogeniture', skin: [4, 5, 6], hair: [4, 6], clothing: 'southern', m: 'Kumaragiri, Pedakomati Vema, Anavema, Singama, Anapota, Vira Bhadra', f: 'Anitalli, Rudrama, Suramba', h: 'Reddis de Kondavidu, Recherla, Musunuri, Velama' }),
  c({ id: 'kannada', name: 'Kannadigas', group: 'dravidian', color: '#c2503a', region: 'Karnataka', law: 'primogeniture', skin: [4, 5, 6], hair: [4, 6], clothing: 'southern', unit: 'footmen', m: 'Harihara, Bukka, Devaraya, Virupaksha, Kampana, Chikkaraya, Mallikarjuna', f: 'Gangadevi, Tirumalamba, Ganga, Bukkamma', h: 'Sangama, Saluva, Tuluva, Aravidu, Hoysala (lignée)' }),
  c({ id: 'tamil', name: 'Tamouls', group: 'dravidian', color: '#9a3a5a', region: 'Pays tamoul', law: 'primogeniture', skin: [5, 6, 7], hair: [4, 6], clothing: 'southern', m: 'Maravarman, Jatavarman, Parakrama, Vira Pandya, Kulasekhara, Rajaraja', f: 'Mangammal, Lokamahadevi, Kundavai', h: 'Pandya, Chola (lignée), Sambuvaraya, Vanadaraya' }),
  c({ id: 'malayali', name: 'Malayalis', group: 'dravidian', color: '#3a8a5a', region: 'Malabar', law: 'elective', skin: [5, 6], hair: [4, 6], clothing: 'southern', mods: { tax_mult: 0.08 }, m: 'Manavikraman, Ravi Varma, Kerala Varma, Godavarma, Veera Kerala', f: 'Unniyarcha, Lakshmi Bayi, Parvathi', h: 'Zamorins de Calicut, Kolathiri, Venad, Perumpadappu' }),
  c({ id: 'sinhala', name: 'Cinghalais', group: 'indo_aryan', color: '#8a3a3a', region: 'Lanka', law: 'primogeniture', skin: [4, 5, 6], hair: [4, 6], clothing: 'southern', m: 'Vira Alakesvara, Parakramabahu, Bhuvanaikabahu, Vikramabahu, Nissanka', f: 'Sunethra, Ulakudaya, Lilavati', h: 'Alagakkonara, Siri Sanga Bo, Maison de Gampola, Aryacakravarti (Jaffna)' }),
  c({ id: 'gond', name: 'Gonds et peuples des forêts centrales', group: 'dravidian', color: '#5a7a3a', region: 'Gondwana', law: 'elective', skin: [5, 6, 7], hair: [4, 6], clothing: 'tropical', m: 'Sangram Shah, Jadurai, Madan Singh, Hirde Shah, Bakht Buland', f: 'Durgavati, Kamlapati, Sundari', h: 'Rajgond de Garha, Gonds de Chanda, Gonds de Deogarh, Kherla' }),
  c({ id: 'nepali', name: 'Newars et Khas', group: 'indo_aryan', color: '#b0605a', region: 'Himalaya', law: 'primogeniture', skin: [2, 3, 4], hair: [4, 6], clothing: 'robed', m: 'Jayasthiti Malla, Jyotirmalla, Yaksha Malla, Jayadharma, Prithvi Malla', f: 'Rajalla Devi, Jayalakshmi, Riddhi Laxmi', h: 'Malla, Khasa Malla, Doya, Sen de Palpa' }),

  // --- Asie orientale ---------------------------------------------------------
  c({ id: 'han', name: 'Chinois (Han)', group: 'sinitic', color: '#b83a2a', region: 'Chine', law: 'primogeniture', skin: [1, 2, 3], hair: [4, 6], clothing: 'silk', mods: { tax_mult: 0.08, monthly_prestige: 0.05 }, m: 'Yunwen, Di, Gaochi, Zhanji, Qiji, Yunjiong, Su, Yuanzhang, Fei, Xiaoru, Jin, Tai, Zicheng', f: 'Ma, Xu, Zhang, Sun, Hu, Wu, Guo, Ning, Qiong', h: 'Zhu, Xu, Fang, Huang, Qi, Li, Tang, Mu, Yang, Xie, Chen, Liu' }),
  c({ id: 'korean', name: 'Coréens', group: 'koreanic', color: '#3a6aa8', region: 'Corée', law: 'primogeniture', skin: [1, 2], hair: [4, 6], clothing: 'silk', m: 'Bang-gwa, Bang-won, Do, Seong-gye, Je, Hyang, Bang-gan, Jo-jun, Mong-ju', f: 'Wongyeong, Sindeok, Sohon, Jeongan, Myeongdeok', h: 'Yi de Jeonju, Min de Yeoheung, Jeong, Kwon, Ha, Jo, Shim' }),
  c({ id: 'japanese', name: 'Japonais', group: 'japonic', color: '#c23a4a', region: 'Japon', law: 'primogeniture', skin: [1, 2], hair: [4, 6], clothing: 'silk', unit: 'archers', m: 'Yoshimitsu, Yoshimochi, Yoshinori, Mitsukane, Mochiuji, Yoshihiro, Mitsuyuki, Mitsumoto, Motoharu, Takauji, Norizane', f: 'Hino Yasuko, Nariko, Tomiko, Koshikibu, Akiko', h: 'Ashikaga, Shiba, Hosokawa, Hatakeyama, Ōuchi, Yamana, Imagawa, Uesugi, Takeda, Shimazu, Ōtomo, Kyōgoku, Akamatsu, Toki' }),
  c({ id: 'ryukyuan', name: 'Ryūkyūans', group: 'japonic', color: '#3a9a8a', region: 'Ryūkyū', law: 'primogeniture', skin: [2, 3], hair: [4, 6], clothing: 'islander', mods: { tax_mult: 0.06 }, m: 'Bunei, Satto, Ōsato, Hanashi, Shō Hashi, Shō Shishō, Min, Taromai', f: 'Noro, Kikoe-ōgimi, Umi', h: 'Satto, Shō, Ōsato, Hokuzan, Nanzan' }),
  c({ id: 'jurchen', name: 'Jurchens', group: 'tungusic', color: '#4a6a8a', region: 'Mandchourie', law: 'seniority', skin: [1, 2], hair: [4, 6], clothing: 'steppe', unit: 'horse_archers', m: 'Ahacu, Mentemu, Wangaoha, Cungšan, Fanca, Ligui', f: 'Nurgan, Ayan, Hada', h: 'Aisin Gioro, Huligai, Odoli, Tumen, Nara' }),
  c({ id: 'ainu', name: 'Aïnous', group: 'ainu', color: '#7a9a8a', region: 'Ezo', law: 'elective', skin: [1, 2], hair: [3, 4], clothing: 'northern', m: 'Koshamain, Shakushain, Onibishi, Chipaya, Kamuy', f: 'Kinas, Menoko, Shirika', h: 'Kotan de Shiraoi, Kotan d’Ishikari, Kotan de Menashi' }),
  c({ id: 'yi', name: 'Peuples des hautes terres du Sud-Ouest', group: 'tibeto_burman', color: '#8a4a8a', region: 'Yunnan et Guizhou', law: 'elective', skin: [2, 3, 4], hair: [4, 6], clothing: 'tropical', m: 'Ahe, Mujia, Anqian, Siqie, Longba, Azhe', f: 'Shezhe, Aniu, Ayi', h: 'Mu de Lijiang, Tusi de Shuixi, An, Yang de Bozhou, Cen' }),

  // --- Asie du Sud-Est ---------------------------------------------------------
  c({ id: 'burmese', name: 'Birmans', group: 'tibeto_burman', color: '#b0703a', region: 'Birmanie', law: 'primogeniture', skin: [3, 4], hair: [4, 6], clothing: 'tropical', m: 'Minkhaung, Swa Saw Ke, Tarabya, Minye Kyawswa, Thihathu, Mohnyin Thado', f: 'Shin Saw Pu, Shin Mi-Nauk, Saw Omma, Soe Min', h: 'Maison d’Ava, Pinya, Mohnyin, Sagaing' }),
  c({ id: 'mon', name: 'Môns', group: 'austroasiatic', color: '#3a8ab0', region: 'Basse-Birmanie', law: 'primogeniture', skin: [3, 4], hair: [4, 6], clothing: 'tropical', mods: { tax_mult: 0.06 }, m: 'Razadarit, Binnya U, Binnya Dhammaraza, Binnya Ran, Smim Byat', f: 'Shin Saw Pu, Talamidaw, Piya Yaza Dewi', h: 'Wareru, Hanthawaddy, Maison de Martaban' }),
  c({ id: 'shan', name: 'Shans et Tai du Nord', group: 'tai', color: '#6a9a3a', region: 'États shans', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'tropical', m: 'Tho Kho Bwa, Si Kan Fa, Hkun Hsang, Sao Hom Hpa, Sao Hkun', f: 'Nang Kham, Nang Mo, Sao Nang', h: 'Mong Mao, Hsenwi, Mohnyin, Kengtung, Mong Yang' }),
  c({ id: 'thai', name: 'Siamois', group: 'tai', color: '#c9983a', region: 'Siam', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'tropical', m: 'Ramaracha, Intharacha, Borommaracha, Ramesuan, Mahathammaracha, Sam Phraya', f: 'Suriyothai, Sri Chulalak, Mahathewi', h: 'Uthong, Suphannaphum, Phra Ruang (Sukhothai)' }),
  c({ id: 'lanna', name: 'Tai Yuan (Lan Na)', group: 'tai', color: '#9ab03a', region: 'Lan Na', law: 'primogeniture', skin: [3, 4], hair: [4, 6], clothing: 'tropical', m: 'Saen Mueang Ma, Sam Fang Kaen, Tilokaraj, Kue Na, Phayu', f: 'Chiraprapha, Maha Thewi, Wisutthithewi', h: 'Mangrai' }),
  c({ id: 'lao', name: 'Lao', group: 'tai', color: '#5ab08a', region: 'Lan Xang', law: 'primogeniture', skin: [3, 4], hair: [4, 6], clothing: 'tropical', m: 'Samsenthai, Lan Kham Deng, Fa Ngum, Sai Tia Kaphut, Vongsa', f: 'Keo Keng Nya, Maha Devi, Nang Keo', h: 'Khun Lo (Lan Xang)' }),
  c({ id: 'khmer', name: 'Khmers', group: 'austroasiatic', color: '#8a6a3a', region: 'Cambodge', law: 'primogeniture', skin: [4, 5], hair: [4, 6], clothing: 'tropical', m: 'Ponhea Yat, Barom Reachea, Kalamegha, Srei Sokonthor, Thommo Soccorach', f: 'Indradevi, Sujata, Chan Srey', h: 'Maison d’Angkor, Maison de Chaktomuk' }),
  c({ id: 'viet', name: 'Viêts', group: 'austroasiatic', color: '#c23a3a', region: 'Đại Việt', law: 'primogeniture', skin: [2, 3], hair: [4, 6], clothing: 'silk', unit: 'footmen', m: 'Quý Ly, Hán Thương, Nguyên Trừng, Thiếu Đế, Ngung, Lợi, Trãi, Quý Khoáng', f: 'Huy Ninh, Thánh Ngâu, Ngọc Trân', h: 'Hồ, Trần, Lê, Nguyễn, Trịnh, Mạc' }),
  c({ id: 'cham', name: 'Chams', group: 'austronesian', color: '#3ab09a', region: 'Champa', law: 'elective', skin: [3, 4, 5], hair: [4, 6], clothing: 'tropical', m: 'Jaya Simhavarman, Indravarman, Maha Vijaya, Ko Cheng, Che Bong Nga', f: 'Tapasi, Huyền Trân, Parameshvari', h: 'Maison de Vijaya, Maison de Panduranga' }),
  c({ id: 'malay', name: 'Malais', group: 'austronesian', color: '#3a9a5a', region: 'Détroits', law: 'elective', skin: [3, 4, 5], hair: [4, 6], clothing: 'islander', mods: { tax_mult: 0.08 }, m: 'Parameswara, Iskandar, Megat, Muhammad, Muzaffar, Zainal Abidin, Sultan Ahmad', f: 'Tun Kudu, Puteri Hang Li Po, Tun Fatimah', h: 'Maison de Palembang, Malacca, Samudera Pasai, Kedah, Pahang' }),
  c({ id: 'javanese', name: 'Javanais', group: 'austronesian', color: '#b03a3a', region: 'Java', law: 'primogeniture', skin: [3, 4, 5], hair: [4, 6], clothing: 'islander', mods: { tax_mult: 0.08 }, m: 'Wikramawardhana, Bhre Wirabhumi, Kertawijaya, Hayam Wuruk, Rajasawardhana, Gajah Mada', f: 'Kusumawardhani, Suhita, Tribhuwana, Rajapatni', h: 'Rajasa (Majapahit), Wengker, Kahuripan, Daha, Pajang' }),
  c({ id: 'sundanese', name: 'Soundanais', group: 'austronesian', color: '#8ab03a', region: 'Sunda', law: 'primogeniture', skin: [3, 4], hair: [4, 6], clothing: 'islander', m: 'Niskala Wastu Kancana, Prabu Wangi, Sri Baduga, Dewa Niskala', f: 'Dyah Pitaloka, Mayang Sunda', h: 'Maison de Galuh, Maison de Pakuan' }),
  c({ id: 'bugis', name: 'Bugis, Makassar et peuples de l’Est', group: 'austronesian', color: '#6a3ab0', region: 'Célèbes et Moluques', law: 'elective', skin: [4, 5], hair: [4, 6], clothing: 'islander', unit: 'footmen', m: 'La Galigo, Karaeng, Marhum, Zainal, Cico, Kaicil', f: 'We Tenriabeng, Datu, Boki', h: 'Luwu, Bone, Gowa, Ternate, Tidore, Bacan' }),
  c({ id: 'philippine', name: 'Peuples des Philippines', group: 'austronesian', color: '#b08a3a', region: 'Philippines', law: 'elective', skin: [3, 4, 5], hair: [4, 6], clothing: 'islander', m: 'Lakandula, Sulayman, Humabon, Lapulapu, Batara, Kabungsuwan, Baginda', f: 'Urduja, Humamay, Dayang', h: 'Tondo, Maynila, Cebu, Sulu (Baguinda), Butuan, Ma-i' }),
  c({ id: 'dayak', name: 'Peuples de Bornéo', group: 'austronesian', color: '#5a8a4a', region: 'Bornéo', law: 'elective', skin: [3, 4, 5], hair: [4, 6], clothing: 'tropical', m: 'Awang Alak Betatar, Abdul Majid, Ahmad, Temenggong, Sang Aji', f: 'Dayang, Puteri Ratna', h: 'Brunei, Sambas, Banjar, Kutai, Tanjungpura' }),
  c({ id: 'papuan', name: 'Papous et Mélanésiens', group: 'papuan', color: '#6a4a2a', region: 'Nouvelle-Guinée', law: 'elective', skin: [6, 7, 8], hair: [4, 6], clothing: 'tropical', m: 'Kumul, Wapi, Tamba, Bunai, Kopi, Mek', f: 'Wena, Kila, Siri', h: 'Clan des hautes vallées, Clan du Sepik, Clan côtier, Clan du Fly' }),

  // --- Afrique subsaharienne ----------------------------------------------------
  c({ id: 'mande', name: 'Mandingues', group: 'mande', color: '#c9903a', region: 'Mali', law: 'seniority', skin: [6, 7, 8], hair: [4, 6], clothing: 'robed', unit: 'heavy_cavalry', mods: { tax_mult: 0.05 }, m: 'Mansa Musa, Maghan, Sulayman, Mari Djata, Moussa, Ouali, Sandaki, Kankou, Mahmud', f: 'Kassi, Sogolon, Nana, Nare, Djata', h: 'Keïta, Traoré, Konaté, Kamara, Kouyaté, Cissé' }),
  c({ id: 'soninke', name: 'Soninkés et Peuls', group: 'mande', color: '#a8703a', region: 'Sahel occidental', law: 'seniority', skin: [5, 6, 7], hair: [4, 6], clothing: 'robed', unit: 'light_cavalry', m: 'Koli Tenguella, Dinga, Samba, Demba, Hamadi, Galo', f: 'Fatoumata, Koumba, Diaba', h: 'Cissé, Tenguella, Sy, Diallo, Bâ' }),
  c({ id: 'wolof', name: 'Wolofs et Sérères', group: 'atlantic', color: '#3a7a9a', region: 'Sénégambie', law: 'elective', skin: [6, 7, 8], hair: [4, 6], clothing: 'robed', unit: 'light_cavalry', m: 'Ndiadiane Ndiaye, Birayma Ndiklam, Leléfoulifak, Boukar, Maysa Wali', f: 'Linguère, Ndate, Yacine', h: 'Ndiaye, Fall, Guéladio, Joof, Diouf' }),
  c({ id: 'songhai', name: 'Songhaïs', group: 'nilo_saharan', color: '#b8603a', region: 'Boucle du Niger', law: 'seniority', skin: [6, 7], hair: [4, 6], clothing: 'robed', unit: 'light_cavalry', m: 'Sonni Madawu, Sonni Muhammad Dao, Sonni Ali, Askia, Suleiman Dandi', f: 'Kassaï, Bana, Zara', h: 'Sonni, Dia, Askia (lignée)' }),
  c({ id: 'mossi', name: 'Mossis', group: 'gur', color: '#8a8a3a', region: 'Plateau mossi', law: 'seniority', skin: [6, 7, 8], hair: [4, 6], clothing: 'robed', unit: 'light_cavalry', m: 'Naaba Oubri, Naaba Zoungrana, Naaba Kouda, Naaba Nasbire, Ouedraogo', f: 'Yennenga, Poko, Pougbila', h: 'Nakomsé, Ouedraogo, Yatenga, Ouagadougou' }),
  c({ id: 'hausa', name: 'Haoussas', group: 'chadic', color: '#6a8a3a', region: 'Pays haoussa', law: 'elective', skin: [6, 7, 8], hair: [4, 6], clothing: 'robed', mods: { tax_mult: 0.06 }, m: 'Kanajeji, Umaru, Dauda, Abdullahi Burja, Yaji, Muhammad Rumfa, Bawa', f: 'Amina, Bakwa Turunku, Zaria, Daura', h: 'Bagauda (Kano), Daura, Katsina, Zazzau, Gobir' }),
  c({ id: 'kanuri', name: 'Kanouris', group: 'nilo_saharan', color: '#8a5a3a', region: 'Kanem-Bornou', law: 'seniority', skin: [6, 7], hair: [4, 6], clothing: 'robed', unit: 'heavy_cavalry', m: 'Umar ibn Idris, Uthman Kalnama, Dunama, Biri, Idris, Kaday, Ali Gaji', f: 'Aisa Kili, Gumsu, Magira', h: 'Sayfawa, Bulala, Kanembu' }),
  c({ id: 'yoruba', name: 'Yorubas', group: 'volta_niger', color: '#b0503a', region: 'Pays yoruba', law: 'elective', skin: [6, 7, 8], hair: [4, 6], clothing: 'tropical', m: 'Oranmiyan, Onigbogi, Ofinran, Ajaka, Sango, Obalufon, Oluaso', f: 'Moremi, Oya, Orompoto, Luwo', h: 'Ife (Ooni), Oyo (Alaafin), Owu, Ijebu, Egba' }),
  c({ id: 'edo', name: 'Edos (Bénin)', group: 'volta_niger', color: '#9a3a3a', region: 'Bénin', law: 'primogeniture', skin: [6, 7, 8], hair: [4, 6], clothing: 'tropical', m: 'Oguola, Edoni, Udagbedo, Ohen, Egbeka, Orobiru, Ewuare', f: 'Idia, Emotan, Iyoba', h: 'Maison d’Eweka, Uzama, Iyase' }),
  c({ id: 'akan', name: 'Akans', group: 'kwa', color: '#c9b03a', region: 'Côte de l’or', law: 'elective', skin: [6, 7, 8], hair: [4, 6], clothing: 'tropical', mods: { tax_mult: 0.06 }, m: 'Kwaku, Kofi, Kwame, Obiri, Oti Akenten, Nana, Ansa', f: 'Abena, Akua, Yaa, Ama, Afua', h: 'Bono, Denkyira, Adansi, Akwamu, Oyoko' }),
  c({ id: 'igbo', name: 'Igbos et peuples du delta', group: 'volta_niger', color: '#5a9a3a', region: 'Basse-Niger', law: 'elective', skin: [6, 7, 8], hair: [4, 6], clothing: 'tropical', m: 'Eri, Nri Ifikuanim, Nri Namoke, Obi, Okonkwo, Chukwu', f: 'Ada, Ngozi, Nkechi, Uzoamaka', h: 'Nri, Aro, Arochukwu, Onitsha' }),
  c({ id: 'amhara', name: 'Amharas et Tigréens', group: 'semitic_ethiopian', color: '#3a8a3a', region: 'Éthiopie', law: 'primogeniture', skin: [4, 5, 6], hair: [4, 6], clothing: 'robed', unit: 'footmen', m: 'Dawit, Tewodros, Yeshaq, Zara Yaqob, Newaya Maryam, Andreyas, Sayfa Arad', f: 'Egzi Kebra, Seyon Mogesa, Eleni, Zan Kasa', h: 'Maison salomonide, Bahr negash, Shewa, Tigray' }),
  c({ id: 'somali', name: 'Somalis, Afars et Hararis', group: 'cushitic', color: '#a8a03a', region: 'Corne', law: 'elective', skin: [4, 5, 6], hair: [4, 6], clothing: 'robed', unit: 'light_cavalry', m: 'Sa’ad ad-Din, Sabr ad-Din, Mansur, Jamal ad-Din, Haqq ad-Din, Ahmad, Abu Bakr', f: 'Fatima, Bati del Wambara, Halima', h: 'Walashma, Ajuran, Garen, Mudaffar, Harla' }),
  c({ id: 'oromo', name: 'Peuples couchitiques du Sud', group: 'cushitic', color: '#6a7a3a', region: 'Hauts plateaux méridionaux', law: 'elective', skin: [5, 6, 7], hair: [4, 6], clothing: 'robed', m: 'Abba Jifar, Dullo, Galo, Borana, Tulama, Wolde', f: 'Ayyo, Ebise, Hawwi', h: 'Borana, Barentu, Sidama, Hadiya, Kaffa' }),
  c({ id: 'swahili', name: 'Swahilis', group: 'bantu', color: '#3a9ab0', region: 'Côte swahilie', law: 'elective', skin: [5, 6, 7], hair: [4, 6], clothing: 'islander', mods: { tax_mult: 0.1 }, m: 'Hasan bin Sulaiman, Sulaiman, Muhammad, Ali, Ibrahim, Fumo Liongo', f: 'Mwana Mkisi, Fatuma, Mwana Kupona', h: 'Mahdali (Kilwa), Nabahani (Pate), Shirazi, Mazrui, Maison de Malindi' }),
  c({ id: 'great_lakes', name: 'Peuples des Grands Lacs', group: 'bantu', color: '#8a3a6a', region: 'Grands Lacs', law: 'elective', skin: [6, 7, 8], hair: [4, 6], clothing: 'tropical', m: 'Ndahiro, Ruhinda, Kimera, Wamara, Ntare, Ruganzu, Isimbwa', f: 'Nyabingi, Nyiraruganzu, Njunaki', h: 'Bacwezi, Babito, Bahinda, Banyiginya, Abakama' }),
  c({ id: 'kongo', name: 'Kongos et peuples de l’Atlantique central', group: 'bantu', color: '#b0703a', region: 'Kongo', law: 'elective', skin: [6, 7, 8], hair: [4, 6], clothing: 'tropical', m: 'Lukeni lua Nimi, Nanga, Nkuwu, Nzinga, Mbemba, Nlaza', f: 'Nzinga, Kimpa, Lukeni, Mbanza', h: 'Kilukeni, Kinlaza, Kimpanzu, Soyo, Loango' }),
  c({ id: 'luba', name: 'Lubas et peuples de la savane', group: 'bantu', color: '#7a8a3a', region: 'Katanga', law: 'elective', skin: [6, 7, 8], hair: [4, 6], clothing: 'tropical', m: 'Kongolo, Kalala Ilunga, Ilunga Mbidi, Kasongo, Mwata', f: 'Bulanda, Rweej, Mwadi', h: 'Balopwe, Lunda, Kanyok, Songye' }),
  c({ id: 'shona', name: 'Shonas', group: 'bantu', color: '#a85a3a', region: 'Plateau du Zimbabwe', law: 'elective', skin: [6, 7, 8], hair: [4, 6], clothing: 'tropical', mods: { tax_mult: 0.05 }, m: 'Nyatsimba Mutota, Matope, Mukombero, Chikuyo, Changamire', f: 'Nehanda, Chaminuka, Mbuya', h: 'Maison de Zimbabwe, Mutapa, Torwa, Changamire' }),
  c({ id: 'nguni', name: 'Nguni, Sotho et Tswana', group: 'bantu', color: '#6a5a3a', region: 'Afrique australe', law: 'seniority', skin: [6, 7, 8], hair: [4, 6], clothing: 'tropical', m: 'Malandela, Mnguni, Tshawe, Mohlomi, Masilo, Mogale', f: 'Nandi, Mmanthatisi, Nomvula', h: 'Clan Tshawe, Clan Hurutshe, Clan Kwena, Clan Dlamini' }),
  c({ id: 'khoisan', name: 'Khoïkhoï et San', group: 'khoisan', color: '#b8a07a', region: 'Désert et côtes australes', law: 'elective', skin: [4, 5], hair: [4, 6], clothing: 'tropical', m: '!Kung, Gaob, Hei-!gaib, Kx’au, Tsaob', f: '!Ai, Nǂao, Xaba', h: 'Clan des Cochoqua, Clan des Nama, Clan des Gonaqua, Bande du Kalahari' }),
  c({ id: 'malagasy', name: 'Malgaches', group: 'austronesian', color: '#3ab06a', region: 'Madagascar', law: 'elective', skin: [4, 5, 6], hair: [4, 6], clothing: 'islander', m: 'Andriamanelo, Ralambo, Andrianjaka, Andriamasinavalona, Rangita', f: 'Rafohy, Rangita, Rasoherina', h: 'Merina, Sakalava, Betsileo, Antemoro, Bara' }),
  c({ id: 'nilotic', name: 'Peuples nilotiques', group: 'nilo_saharan', color: '#5a6a3a', region: 'Haut-Nil', law: 'elective', skin: [7, 8], hair: [4, 6], clothing: 'tropical', m: 'Nyikang, Dak, Nyadwai, Aywel, Deng, Garang', f: 'Abuk, Nyachol, Achol', h: 'Shilluk, Dinka, Nuer, Luo, Anuak' }),

  // --- Amériques --------------------------------------------------------------
  c({ id: 'nahua', name: 'Nahuas', group: 'uto_aztecan', color: '#3a9ab0', region: 'Vallée de Mexico', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'plains', unit: 'footmen', m: 'Tezozomoc, Huitzilihuitl, Acamapichtli, Ixtlilxochitl, Maxtla, Chimalpopoca, Itzcoatl, Techotlalatzin, Tlacaelel', f: 'Ayauhcihuatl, Miahuaxihuitl, Tecuichpoch, Matlalcihuatzin', h: 'Tepanecs d’Azcapotzalco, Mexicas de Tenochtitlan, Acolhuas de Texcoco, Tlaxcaltèques, Chalcas' }),
  c({ id: 'maya', name: 'Mayas', group: 'mayan', color: '#3ab07a', region: 'Yucatán et Guatemala', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'plains', m: 'Ah Xupan, Nachi Cocom, Kʼiche Kʼuxkap, Qʼuqʼumatz, Kaqchikel, Tutul Xiu, Kan Ek', f: 'Ix Chel, Ix Kʼabel, Ix Zak', h: 'Cocom, Xiu, Canul, Kʼicheʼ, Kaqchikel, Itzá' }),
  c({ id: 'oaxacan', name: 'Mixtèques et Zapotèques', group: 'otomanguean', color: '#b0503a', region: 'Oaxaca', law: 'primogeniture', skin: [3, 4], hair: [4, 6], clothing: 'plains', m: 'Cosijoeza, Zaachila, Ocho Venado, Dzahui, Cocijopii', f: 'Seis Mono, Pelaxilla, Donaji', h: 'Tilantongo, Zaachila, Tututepec, Coixtlahuaca' }),
  c({ id: 'purepecha', name: 'Purépechas', group: 'isolate', color: '#6a3a8a', region: 'Michoacán', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'plains', m: 'Tariácuri, Hiripan, Tangaxoan, Hiquingare, Tzitzipandácuare', f: 'Eréndira, Atzimba', h: 'Uacúsecha, Pátzcuaro, Tzintzuntzan, Ihuatzio' }),
  c({ id: 'quechua', name: 'Quechuas', group: 'quechuan', color: '#c9803a', region: 'Andes centrales', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'andean', unit: 'footmen', m: 'Viracocha Inca, Yawar Huacac, Inca Roca, Pachacuti, Inca Urcon, Tupac, Tocay Capac, Uscovilca', f: 'Mama Runtu, Mama Chiquia, Mama Ocllo, Mama Anahuarque', h: 'Hurin Cusco, Hanan Cusco, Chanka, Ayarmaca, Quilliscacha, Chinchaysuyu' }),
  c({ id: 'aymara', name: 'Aymaras', group: 'aymaran', color: '#8a6a3a', region: 'Altiplano', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'andean', m: 'Cari, Zapana, Chuchi Capac, Apo Cari', f: 'Mama Cora, Kusi', h: 'Lupaqa, Colla, Pacajes, Charcas, Carangas' }),
  c({ id: 'chimu', name: 'Chimús et peuples de la côte', group: 'andean_coast', color: '#3a6a9a', region: 'Côte nord du Pérou', law: 'primogeniture', skin: [3, 4], hair: [4, 6], clothing: 'andean', mods: { tax_mult: 0.06 }, m: 'Minchancaman, Guacricur, Nancenpinco, Tacaynamo, Ñancen', f: 'Chimor Nusta, Fempellec', h: 'Chimor, Chincha, Sicán, Chancay, Ychsma' }),
  c({ id: 'muisca', name: 'Muiscas et peuples chibchas', group: 'chibchan', color: '#b0a03a', region: 'Hauts plateaux du Nord', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'andean', m: 'Saguamanchica, Meicuchuca, Nemequene, Hunzahúa, Quemuenchatocha, Tisquesusa', f: 'Furachogua, Bachué, Chía', h: 'Zipazgo de Bacatá, Zacazgo de Hunza, Iraca, Tundama, Tairona' }),
  c({ id: 'taino', name: 'Taïnos', group: 'arawakan', color: '#3ab0b0', region: 'Grandes Antilles', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'islander', m: 'Guarionex, Caonabo, Behechio, Guacanagarí, Hatuey, Agüeybaná', f: 'Anacaona, Higuamota, Yuisa', h: 'Cacicazgo de Maguá, Maguana, Jaragua, Higüey, Marién' }),
  c({ id: 'carib', name: 'Peuples caraïbes et arawaks', group: 'cariban', color: '#6ab03a', region: 'Petites Antilles et Guyanes', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'tropical', m: 'Kairi, Tamanaco, Guaicaipuro, Yaruro, Kalinago', f: 'Urquía, Mapuy', h: 'Kalinago, Lokono, Kariña, Warao' }),
  c({ id: 'tupi', name: 'Tupis et Guaranis', group: 'tupian', color: '#3a8a3a', region: 'Côte et forêts d’Amérique du Sud', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'tropical', m: 'Cunhambebe, Tibiriçá, Aimberê, Arariboia, Guaraci, Sepé', f: 'Paraguaçu, Bartira, Moema', h: 'Tupinambá, Tupiniquim, Carijó, Tamoio, Potiguara' }),
  c({ id: 'amazonian', name: 'Peuples d’Amazonie', group: 'amazonian', color: '#2a7a4a', region: 'Amazonie', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'tropical', m: 'Arapari, Tuxaua, Omagua, Yawar, Tapajó', f: 'Iara, Naiá, Jaci', h: 'Chefferie omagua, Chefferie tapajó, Chefferie de Marajó, Chefferie du Xingu' }),
  c({ id: 'mapuche', name: 'Mapuches et peuples australs', group: 'araucanian', color: '#5a6ab0', region: 'Chili et pampas', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'andean', m: 'Lautaro, Caupolicán, Colocolo, Michimalonco, Lincoyán, Pelantaro', f: 'Janequeo, Guacolda, Fresia', h: 'Lof du Biobío, Lof de l’Araucanie, Picunche, Huilliche, Tehuelche' }),
  c({ id: 'mississippian', name: 'Peuples mississippiens', group: 'muskogean', color: '#9a5a3a', region: 'Mississippi et Sud-Est', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'plains', m: 'Tuskaloosa, Chicora, Ocute, Coosa, Pacaha, Casqui, Guachoya', f: 'Dame de Cofitachequi, Tamaha', h: 'Coosa, Cofitachequi, Apalachee, Etowah, Moundville, Natchez' }),
  c({ id: 'iroquoian', name: 'Iroquoiens', group: 'iroquoian', color: '#6a3a3a', region: 'Grands Lacs orientaux', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'plains', m: 'Deganawida, Hiawatha, Atotarho, Donnacona, Tessouat, Skenandoa', f: 'Jigonsaseh, Aataentsic, Tekakwitha', h: 'Onondaga, Mohawk, Seneca, Oneida, Cayuga, Wendat, Stadaconé' }),
  c({ id: 'algonquian', name: 'Algonquiens', group: 'algic', color: '#4a7a6a', region: 'Forêts du Nord-Est', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'plains', m: 'Wahunsenacawh, Massasoit, Metacom, Miantonomi, Ninigret, Opechancanough', f: 'Pocahontas, Weetamoo, Awashonks', h: 'Powhatan, Wampanoag, Lenape, Mi’kmaq, Anishinaabe, Cree' }),
  c({ id: 'plains', name: 'Peuples des Plaines et des Prairies', group: 'siouan', color: '#b09a5a', region: 'Grandes Plaines', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'plains', m: 'Tatanka, Mahpiya, Wanbli, Ohiyesa, Kangi, Hehaka', f: 'Wichapi, Winona, Tahcawin', h: 'Pawnee, Caddo, Wichita, Mandan, Omaha, Hidatsa' }),
  c({ id: 'puebloan', name: 'Pueblos et peuples du désert', group: 'uto_aztecan', color: '#c98a5a', region: 'Sud-Ouest', law: 'elective', skin: [3, 4], hair: [4, 6], clothing: 'plains', m: 'Popé, Tsawa, Kiva, Tewa, Hopi, Oraibi', f: 'Kokyangwuti, Pamisa', h: 'Hopi, Zuni, Tewa, Keres, Hohokam, O’odham' }),
  c({ id: 'pacific_nw', name: 'Peuples de la côte Nord-Ouest', group: 'northwest', color: '#3a5a8a', region: 'Côte Pacifique Nord', law: 'elective', skin: [2, 3], hair: [4, 6], clothing: 'northern', m: 'Maquinna, Wickaninnish, Kwah, Sealth, Ts’ehl', f: 'Tlingit, Kwiyitsum, Tsauwu', h: 'Tlingit, Haida, Kwakwaka’wakw, Nuu-chah-nulth, Coast Salish, Chinook' }),
  c({ id: 'athabaskan', name: 'Athapascans et peuples subarctiques', group: 'athabaskan', color: '#7a8a9a', region: 'Subarctique', law: 'elective', skin: [2, 3], hair: [4, 6], clothing: 'northern', m: 'Matonabbee, Akaitcho, Denetsa, Sahtu', f: 'Thanadelthur, Tsaaii', h: 'Dene, Gwich’in, Dena’ina, Chipewyan, Tłı̨chǫ' }),
  c({ id: 'inuit', name: 'Inuits', group: 'eskimo_aleut', color: '#9ab0c0', region: 'Arctique', law: 'elective', skin: [1, 2, 3], hair: [4, 6], clothing: 'northern', m: 'Qitdlarssuaq, Aua, Nanook, Uqsuralik, Kallak', f: 'Sedna, Arnaq, Nuliajuk', h: 'Thulé du Groenland, Thulé du Labrador, Iñupiat, Yupik, Unangan' }),

  // --- Océanie ----------------------------------------------------------------
  c({ id: 'aboriginal', name: 'Nations aborigènes', group: 'aboriginal', color: '#b0603a', region: 'Australie', law: 'elective', skin: [6, 7, 8], hair: [2, 4, 6], clothing: 'tropical', m: 'Bennelong, Pemulwuy, Yagan, Windradyne, Mullawirraburka', f: 'Truganini, Barangaroo, Fanny Balbuk', h: 'Nation eora, Nation noongar, Nation yolngu, Nation arrernte, Nation wiradjuri, Nation kaurna' }),
  c({ id: 'maori', name: 'Māoris', group: 'polynesian', color: '#3a6a5a', region: 'Aotearoa', law: 'elective', skin: [3, 4, 5], hair: [4, 6], clothing: 'islander', unit: 'footmen', m: 'Tūwharetoa, Kahungunu, Tamatea, Te Rauparaha, Hinga, Ngātoro', f: 'Hinemoa, Wairaka, Mahinaarangi', h: 'Ngāi Tahu, Ngāti Tūwharetoa, Ngāpuhi, Waikato, Te Arawa, Ngāti Porou' }),
  c({ id: 'polynesian', name: 'Polynésiens', group: 'polynesian', color: '#3ab0d0', region: 'Polynésie', law: 'primogeniture', skin: [3, 4, 5], hair: [4, 6], clothing: 'islander', m: 'Tuʻi Tonga, Momo, Tuʻitātui, Kauʻulufonua, Līloa, Kalaunuiohua, Tafaʻifa, Malietoa', f: 'Salamasina, Kaʻahumanu, Nāʻiliʻili, Tuputupu', h: 'Tuʻi Tonga, Tuʻi Haʻatakalaua, Pilihonua (Hawaiʻi), Malietoa (Samoa), Pōmare (Tahiti)' }),
  c({ id: 'micronesian', name: 'Micronésiens et Mélanésiens des îles', group: 'austronesian', color: '#5ab0a0', region: 'Micronésie et Fidji', law: 'elective', skin: [4, 5, 6], hair: [4, 6], clothing: 'islander', m: 'Saudeleur, Isokelekel, Ratu, Tui Viti, Roko', f: 'Adi, Litia, Tamara', h: 'Saudeleur, Nan Madol, Bau, Rewa, Lau' }),
];

export const CULTURE_1400_NAMES = CULTURE_NAMES;
