import type { Effect, EventDef, ScopeRef } from '@ttc/shared';

/**
 * Événements de cour, de conseil, de vassalité, d'économie, de culture et de
 * religion. Chaînes :
 *  - council_ledger_discrepancy → council_ledger_investigation (détournement au conseil)
 *  - vassals_overmighty_murmurs → vassals_overmighty_plot | vassals_overmighty_defiance (vassal trop puissant)
 *  - economy_poor_harvest → economy_famine_spreads → economy_famine_riots (famine)
 *  - religion_preacher_capital → religion_heresy_spreads → religion_heresy_schism (hérésie)
 */

/** Opinion d'un personnage envers le destinataire de l'événement. */
const op = (who: ScopeRef, value: number, reason: string, months?: number): Effect => ({
  addOpinion: { towards: 'root', value, reason, ...(months ? { months } : {}) },
  who,
});

const HOLY_RELIC: Effect = {
  addModifier: { id: 'religion_holy_relic', values: { monthly_fervor: 0.4, monthly_prestige: 0.2 } },
};

export const EVENTS_COURT: EventDef[] = [
  // -------------------------------------------------------------------------
  // Cour
  // -------------------------------------------------------------------------
  {
    id: 'court_petitioner_miller',
    category: 'court',
    title: 'La meule et la dette',
    text: 'Un meunier des faubourgs de {province.name} s’agenouille devant votre trône, de la farine encore aux manches. L’hiver dernier, il a emprunté pour réparer sa roue ; le prêteur réclame désormais le moulin entier, en vertu d’un contrat que le pauvre homme ne sait pas lire. La salle s’est tue. Chacun attend de voir si vous pencherez du côté de la lettre ou de celui de la miséricorde.',
    illustration: 'throne_room',
    trigger: 'pulse',
    weight: 10,
    portraits: ['root'],
    choices: [
      {
        id: 'pay_debt',
        label: '« Le trésor rachètera cette dette. »',
        cost: { gold: 40 },
        effects: [{ addPrestige: 25 }, { changeControl: 3 }],
        tags: ['generous', 'compassionate'],
        ai: { base: 10, traits: { generous: 20, compassionate: 15, greedy: -15 }, personality: { compassion: 15, greed: -10 } },
      },
      {
        id: 'tear_contract',
        label: '« Un contrat que l’on ne peut lire ne lie personne. »',
        tooltip: 'Le peuple applaudira ; les prêteurs, beaucoup moins.',
        effects: [{ changeControl: 5 }, { addAuthority: -15 }],
        tags: ['compassionate'],
        ai: { base: 8, traits: { arbitrary: 15, compassionate: 10, just: -10 }, personality: { compassion: 10, honor: -5 } },
      },
      {
        id: 'uphold_contract',
        label: '« La loi est la loi. Le moulin change de maître. »',
        effects: [{ addAuthority: 15 }, { changeControl: -3 }],
        ai: { base: 10, traits: { just: 15, greedy: 5, compassionate: -15 }, personality: { honor: 10, compassion: -10 } },
      },
    ],
  },
  {
    id: 'court_wandering_poet',
    category: 'court',
    title: 'Le poète sans maître',
    text: 'Un poète à la cape usée par les routes s’est présenté à vos portes, un luth en bandoulière et une réputation qui le précède : on dit qu’il a fait pleurer une cour entière et rire une autre aux dépens de son seigneur. Il cherche un protecteur pour l’hiver et promet en échange des vers qui survivront aux murs de {province.name}. Votre intendant, lui, calcule déjà le prix de son vin.',
    illustration: 'feast',
    trigger: 'pulse',
    weight: 10,
    portraits: ['root'],
    choices: [
      {
        id: 'patronize',
        label: '« Qu’on lui donne une chambre et une pension. »',
        cost: { gold: 60 },
        effects: [
          { spawnCourtier: { traits: ['poet'], skill: 'diplomacy' } },
          { addModifier: { id: 'court_patron_of_letters', months: 36, values: { monthly_prestige: 0.4 } } },
        ],
        tags: ['generous'],
        ai: { base: 10, traits: { generous: 15, sociable: 10, greedy: -20 }, personality: { sociability: 10 } },
      },
      {
        id: 'commission',
        label: '« Une ode à ma gloire, et vous serez payé. »',
        tooltip: 'Les poètes ont la plume imprévisible.',
        cost: { gold: 30 },
        effects: [{ chance: 70, then: [{ addPrestige: 60 }], else: [{ addPrestige: -30 }] }],
        tags: ['ambitious'],
        ai: { base: 8, traits: { arrogant: 20, ambitious: 10, humble: -15 }, personality: { ambition: 10 } },
      },
      {
        id: 'learn_verse',
        label: '« Apprenez-moi plutôt votre art. »',
        conditions: { skill: 'diplomacy', value: { min: 12 } },
        effects: [
          { addStress: -10 },
          { chance: 35, then: [{ addTrait: 'poet' }], else: [{ addSkill: { skill: 'learning', value: 1 } }] },
        ],
        ai: { base: 6, traits: { diligent: 10, sociable: 5 }, personality: { sociability: 5 } },
      },
      {
        id: 'dismiss',
        label: '« Nous n’avons que faire des rimailleurs. »',
        effects: [{ addPrestige: -10 }],
        tags: ['greedy'],
        ai: { base: 8, traits: { greedy: 15, reclusive: 10 }, personality: { greed: 10 } },
      },
    ],
  },
  {
    id: 'court_feast_gone_wrong',
    category: 'court',
    title: 'Le vin de trop',
    text: 'Le banquet touchait à sa fin lorsque {target.fullname}, écarlate et chancelant{target.e}, s’est levé{target.e} pour porter un toast. Au lieu des louanges attendues, les convives ont entendu railler la maigreur des plats, puis l’avarice de votre maison, avant que la grande aiguière ne se renverse sur la nappe brodée. Vos invités guettent maintenant votre réaction, partagés entre la gêne et la gourmandise.',
    illustration: 'feast',
    trigger: 'pulse',
    weight: 10,
    target: { pool: 'courtier' },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'laugh',
        label: '« Voilà bien le seul ici qui ose dire la vérité ! »',
        effects: [{ addPrestige: -15 }, { addStress: -10 }, op('target', 15, 'spared_humiliation')],
        tags: ['humble', 'social'],
        ai: { base: 10, traits: { humble: 15, sociable: 15, arrogant: -20 }, personality: { sociability: 10 } },
      },
      {
        id: 'throw_out',
        label: '« Qu’on {target.le} jette dehors, et qu’{target.il} y cuve son vin. »',
        effects: [{ addAuthority: 10 }, op('target', -25, 'public_humiliation')],
        tags: ['vengeful'],
        ai: { base: 8, traits: { wrathful: 20, arrogant: 10, patient: -10 }, personality: { aggression: 10 } },
      },
      {
        id: 'best_wine',
        label: '« Servez le meilleur vin de nos caves, et oublions ceci. »',
        cost: { gold: 40 },
        effects: [{ addPrestige: 20 }, { addVassalOpinion: 5, reason: 'lavish_host', months: 24 }],
        tags: ['generous', 'forgiving'],
        ai: { base: 10, traits: { generous: 15, greedy: -20 }, personality: { sociability: 5, greed: -10 } },
      },
    ],
  },
  {
    id: 'court_duel_of_honor',
    category: 'court',
    title: 'L’honneur au fil de l’épée',
    text: '{target.fullname} accuse {other.fullname} d’avoir insulté sa famille dans la galerie haute, devant témoins. Les deux courtisans se toisent au pied de votre trône, la main près de la garde. L’offensé réclame réparation par les armes, à l’aube, selon l’ancienne coutume ; l’accusé affirme n’avoir dit que la vérité et relève le défi avec un sourire mauvais. Votre parole seule peut encore les retenir.',
    illustration: 'throne_room',
    trigger: 'pulse',
    weight: 8,
    target: { pool: 'courtier' },
    other: { pool: 'courtier' },
    portraits: ['target', 'other'],
    choices: [
      {
        id: 'allow_duel',
        label: '« Que le fer tranche, puisque les mots ont échoué. »',
        tooltip: 'Un duel à l’aube peut coûter une vie.',
        effects: [
          { addPrestige: 15 },
          op('target', 10, 'granted_satisfaction'),
          {
            chance: 30,
            then: [{ killCharacter: { cause: 'duel' }, who: 'other' }],
            else: [{ chance: 50, then: [{ woundCharacter: true, who: 'target' }], else: [{ woundCharacter: true, who: 'other' }] }],
          },
        ],
        ai: { base: 8, traits: { brave: 15, wrathful: 10, compassionate: -15 }, personality: { aggression: 15 } },
      },
      {
        id: 'forbid',
        label: '« Je n’accorde pas le sang de ma cour à vos querelles. »',
        effects: [{ addAuthority: 10 }, op('target', -10, 'denied_satisfaction')],
        ai: { base: 10, traits: { just: 10, patient: 10 }, personality: { caution: 10 } },
      },
      {
        id: 'reconcile',
        label: '« Vous boirez ce soir à la même coupe, à ma table. »',
        cost: { gold: 30 },
        effects: [
          { addMutualOpinion: { with: 'other', value: 15, reason: 'forced_reconciliation' }, who: 'target' },
          { chance: 25, then: [{ createRelationship: { type: 'friend', with: 'other' }, who: 'target' }] },
        ],
        tags: ['social', 'forgiving'],
        ai: { base: 8, traits: { sociable: 15, compassionate: 5 }, personality: { sociability: 10, compassion: 5 } },
      },
    ],
  },
  {
    id: 'court_tournament_champion',
    category: 'court',
    title: 'Le champion errant',
    text: 'Un chevalier sans bannière est arrivé à {province.name} avec trois chevaux, un écuyer muet et une réputation redoutable : on le dit invaincu dans onze lices. Il propose de défendre les couleurs de votre maison lors d’une joute publique, contre une bourse conséquente, ou d’affronter quiconque, à votre cour, osera croiser la lance avec lui. Les jeunes gens de votre entourage ne parlent plus que de cela.',
    illustration: 'tournament',
    trigger: 'pulse',
    weight: 9,
    portraits: ['root'],
    choices: [
      {
        id: 'host_joust',
        label: '« Dressez les lices ; que le peuple voie ce qu’est la vraie chevalerie. »',
        cost: { gold: 80 },
        effects: [{ addPrestige: 70 }, { addVassalOpinion: 5, reason: 'grand_joust', months: 24 }],
        tags: ['social'],
        ai: { base: 10, traits: { sociable: 10, ambitious: 10, greedy: -15 }, personality: { sociability: 10 } },
      },
      {
        id: 'joust_yourself',
        label: '« Je relèverai moi-même le défi. »',
        tooltip: 'Une victoire ferait votre gloire ; une chute, la risée des tavernes.',
        conditions: { all: [{ age: { max: 50 } }, { skill: 'martial', value: { min: 10 } }] },
        effects: [
          {
            chance: 45,
            then: [{ addPrestige: 150 }, { addStress: -15 }],
            else: [{ addPrestige: -40 }, { woundCharacter: true }],
          },
        ],
        tags: ['brave'],
        ai: { base: 5, traits: { brave: 25, arrogant: 10, craven: -30 }, personality: { aggression: 10, caution: -15 } },
      },
      {
        id: 'hire',
        label: '« Entrez plutôt à mon service. »',
        cost: { gold: 60 },
        effects: [{ spawnCourtier: { traits: ['brave'], skill: 'martial' } }, { addPrestige: 10 }],
        ai: { base: 8, personality: { ambition: 10, aggression: 10 } },
      },
      {
        id: 'decline',
        label: '« Les bouffonneries des lices ne m’intéressent pas. »',
        effects: [{ addPrestige: -10 }],
        tags: ['reclusive'],
        ai: { base: 6, traits: { reclusive: 15, greedy: 10 }, personality: { greed: 5 } },
      },
    ],
  },
  {
    id: 'court_foreign_scholar',
    category: 'court',
    title: 'Les cartes du ciel',
    text: 'Un savant venu d’au-delà des mers demande audience. Il transporte des coffres de manuscrits, un astrolabe de cuivre et des idées troublantes : selon lui, les astres obéissent à des lois qu’un esprit patient peut calculer, et l’on pourrait même en prévoir les bonnes et les mauvaises récoltes. Vos prêtres murmurent qu’il n’y a là qu’orgueil déguisé en science ; vos intendants, eux, dressent l’oreille.',
    illustration: 'library',
    trigger: 'pulse',
    weight: 9,
    target: { pool: 'heir', optional: true },
    portraits: ['root'],
    choices: [
      {
        id: 'sponsor',
        label: '« Qu’il dispose d’une tour et de nos archives. »',
        cost: { gold: 60 },
        effects: [{ addSkill: { skill: 'learning', value: 1 } }, { addFervor: -10 }],
        ai: { base: 10, traits: { diligent: 10, cynical: 10, zealous: -15 }, personality: { zeal: -10 } },
      },
      {
        id: 'tutor_heir',
        label: '« Qu’il instruise plutôt {target.name}. »',
        conditions: { exists: 'target' },
        cost: { gold: 40 },
        effects: [{ addSkill: { skill: 'learning', value: 2 }, who: 'target' }, op('target', 10, 'fine_tutor')],
        ai: { base: 9, traits: { diligent: 5 }, personality: { ambition: 5, compassion: 5 } },
      },
      {
        id: 'expel',
        label: '« Ces calculs frôlent le blasphème. Qu’il reprenne la mer. »',
        effects: [{ addFervor: 20 }, { addPrestige: -10 }],
        tags: ['pious'],
        ai: { base: 6, traits: { zealous: 20, cynical: -15 }, personality: { zeal: 15 } },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Conseil
  // -------------------------------------------------------------------------
  {
    id: 'council_blunder',
    category: 'council',
    title: 'Des registres égarés',
    text: 'Les rôles d’impôt de trois paroisses ont disparu, et avec eux la trace de ce que vos sujets doivent pour l’année. L’enquête remonte jusqu’à {target.fullname}, qui siège à votre conseil : les registres avaient été confiés à un clerc de passage, sans sceau ni inventaire. Le conseil attend votre verdict, et plus d’un de ses membres espère secrètement voir un siège se libérer.',
    illustration: 'council_chamber',
    trigger: 'pulse',
    weight: 10,
    conditions: { hasCouncil: true },
    target: {
      pool: 'councillor',
      where: { all: [{ isRuler: false, who: 'target' }, { skill: 'stewardship', value: { max: 10 }, who: 'target' }] },
    },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'banish',
        label: '« Quittez ma cour. Ce siège exige mieux que la négligence. »',
        tooltip: '{target.name} sera chassé{target.e} de votre cour.',
        effects: [{ banish: true, who: 'target' }, { addAuthority: 15 }],
        ai: { base: 8, traits: { wrathful: 15, arbitrary: 10, patient: -10 }, personality: { compassion: -10 } },
      },
      {
        id: 'reprimand',
        label: '« Vous reconstituerez ces rôles vous-même, un par un. »',
        effects: [{ addGold: -30 }, op('target', -10, 'reprimanded'), { addSkill: { skill: 'stewardship', value: 1 }, who: 'target' }],
        ai: { base: 12, traits: { just: 10, diligent: 10 } },
      },
      {
        id: 'forgive',
        label: '« Chacun a droit à une erreur. Une seule. »',
        effects: [{ addGold: -60 }, op('target', 20, 'forgiven_blunder')],
        tags: ['forgiving', 'compassionate'],
        ai: { base: 8, traits: { compassionate: 15, trusting: 15, greedy: -10 }, personality: { compassion: 10 } },
      },
    ],
  },
  {
    id: 'council_first_report',
    category: 'council',
    title: 'Le mémoire du conseiller',
    text: 'Au terme de longues semaines passées dans vos archives, {target.fullname} dépose sur la table du conseil un épais mémoire relié de cuir. Tout y est consigné : les péages mal perçus, les greniers mal tenus, les villages oubliés des percepteurs. La conclusion est limpide. Quelques réformes suffiraient à remplir vos coffres, à condition de froisser tous ceux qui profitent aujourd’hui du désordre.',
    illustration: 'council_chamber',
    trigger: 'pulse',
    weight: 10,
    conditions: { hasCouncil: true },
    target: { pool: 'councillor', where: { skill: 'stewardship', value: { min: 11 }, who: 'target' } },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'adopt_all',
        label: '« Appliquez tout, et sans délai. »',
        effects: [
          { addModifier: { id: 'council_fiscal_reforms', months: 60, values: { monthly_income_mult: 0.08 } } },
          { addVassalOpinion: -5, reason: 'fiscal_reforms', months: 36 },
          op('target', 10, 'counsel_heeded'),
        ],
        tags: ['ambitious'],
        ai: { base: 10, traits: { diligent: 15, ambitious: 10, lazy: -10 }, personality: { greed: 10 } },
      },
      {
        id: 'tolls_only',
        label: '« Ne touchez qu’aux péages ; laissez les seigneurs en paix. »',
        effects: [{ addGold: 50 }, op('target', 5, 'counsel_heeded')],
        ai: { base: 12, personality: { caution: 10 } },
      },
      {
        id: 'shelve',
        label: '« Beau travail. Qu’on le range aux archives. »',
        effects: [op('target', -15, 'counsel_ignored')],
        ai: { base: 5, traits: { lazy: 20, content: 10 } },
      },
    ],
  },
  {
    id: 'council_demands_honours',
    category: 'council',
    title: 'Le prix de la fidélité',
    text: '{target.fullname} sollicite une audience privée. Voilà des années, vous rappelle-t-on, que ce conseiller sert la couronne sans compter ni ses heures ni ses nuits, tandis que d’autres, moins zélés, reçoivent terres et faveurs. La requête est nette : une pension à la hauteur de tant de services, ou quelque honneur visible qui fasse enfin taire les rieurs de la cour.',
    illustration: 'council_chamber',
    trigger: 'pulse',
    weight: 9,
    conditions: { hasCouncil: true },
    target: { pool: 'councillor' },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'pension',
        label: '« Vous aurez votre pension. »',
        cost: { gold: 75 },
        effects: [op('target', 25, 'rewarded_service')],
        tags: ['generous'],
        ai: { base: 10, traits: { generous: 15, greedy: -20 }, personality: { greed: -10 } },
      },
      {
        id: 'place_of_honour',
        label: '« Vous siégerez à ma droite lors des prochains banquets. »',
        cost: { prestige: 50 },
        effects: [op('target', 20, 'honoured_at_court')],
        ai: { base: 10, traits: { humble: 10 }, personality: { sociability: 10 } },
      },
      {
        id: 'refuse',
        label: '« Le service de la couronne est sa propre récompense. »',
        effects: [{ addAuthority: 5 }, op('target', -25, 'refused_honours')],
        tags: ['greedy'],
        ai: { base: 6, traits: { greedy: 20, arrogant: 15 }, personality: { greed: 10 } },
      },
      {
        id: 'promise',
        label: '« Patientez encore un an ; vous ne serez pas oublié{target.e}. »',
        effects: [op('target', 5, 'vague_promise', 12)],
        tags: ['deceitful'],
        ai: { base: 6, traits: { deceitful: 15, honest: -15 }, personality: { intrigue: 10 } },
      },
    ],
  },
  {
    id: 'council_quarrel',
    category: 'council',
    title: 'Deux voix, un conseil',
    text: 'La séance du conseil a tourné à l’affrontement. {target.fullname} accuse {other.fullname} de saboter ses projets par pure jalousie ; l’accusé rétorque que les idées de son collègue ruineront le royaume avant les prochaines moissons. Les autres conseillers comptent les coups en silence. Tant que ces deux-là se déchireront, rien d’utile ne sortira de cette chambre.',
    illustration: 'council_chamber',
    trigger: 'pulse',
    weight: 8,
    conditions: { hasCouncil: true },
    target: { pool: 'councillor' },
    other: { pool: 'councillor' },
    portraits: ['target', 'other'],
    choices: [
      {
        id: 'back_target',
        label: '« {target.name} a raison. Le débat est clos. »',
        effects: [op('target', 15, 'backed_in_council'), op('other', -20, 'overruled_in_council')],
        ai: { base: 10 },
      },
      {
        id: 'back_other',
        label: '« {other.name} a raison. Le débat est clos. »',
        effects: [op('other', 15, 'backed_in_council'), op('target', -20, 'overruled_in_council')],
        ai: { base: 10 },
      },
      {
        id: 'force_cooperation',
        label: '« Vous rédigerez ce projet ensemble, ou vous quitterez tous deux ce conseil. »',
        tooltip: 'L’épreuve peut rapprocher deux hommes… ou les brouiller à jamais.',
        effects: [
          { addAuthority: 10 },
          {
            chance: 40,
            then: [{ createRelationship: { type: 'friend', with: 'other' }, who: 'target' }],
            else: [{ createRelationship: { type: 'rival', with: 'other' }, who: 'target' }],
          },
        ],
        ai: { base: 8, traits: { wrathful: 10, just: 5 }, personality: { aggression: 5, caution: -5 } },
      },
    ],
  },
  {
    id: 'council_ledger_discrepancy',
    category: 'council',
    title: 'Une colonne qui ne tombe pas juste',
    text: 'Un jeune clerc de votre trésorerie a demandé à vous parler seul à seul, tremblant de sa propre audace. En recopiant les comptes de l’année, il a relevé des sommes qui entrent au registre et n’arrivent jamais dans vos coffres. Toutes les pièces litigieuses portent le paraphe de {target.fullname}, membre de votre conseil. Le clerc jure n’en avoir parlé à personne d’autre, pour l’instant.',
    illustration: 'council_chamber',
    trigger: 'pulse',
    weight: 8,
    cooldownDays: 2920,
    conditions: { hasCouncil: true },
    target: { pool: 'councillor' },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'investigate',
        label: '« Poursuivez discrètement. Je veux des preuves. »',
        tooltip: 'Le clerc vous rendra compte dans quelques mois.',
        cost: { gold: 20 },
        effects: [{ triggerEvent: { id: 'council_ledger_investigation', days: 75 } }],
        ai: { base: 12, traits: { paranoid: 15, diligent: 10 }, personality: { caution: 10 } },
      },
      {
        id: 'confront',
        label: '« Qu’on {target.le} fasse venir sur-le-champ. »',
        effects: [
          {
            chance: 50,
            then: [{ addGold: 60 }, op('target', -20, 'accused_of_theft')],
            else: [{ addPrestige: -20 }, op('target', -30, 'falsely_accused')],
          },
        ],
        tags: ['honest'],
        ai: { base: 8, traits: { wrathful: 15, honest: 10 }, personality: { aggression: 10 } },
      },
      {
        id: 'keep_leverage',
        label: '« Gardez ces feuillets en lieu sûr. Ils me serviront un jour. »',
        effects: [
          { createSecret: { type: 'corruption', knownBy: ['root'] }, who: 'target' },
          { createHook: { on: 'target', years: 10 } },
        ],
        tags: ['deceitful'],
        ai: { base: 6, traits: { deceitful: 15, honest: -15 }, personality: { intrigue: 15 } },
      },
      {
        id: 'punish_clerk',
        label: '« Un clerc qui calomnie un conseiller ? Qu’on le fouette. »',
        effects: [op('target', 10, 'defended_honour'), { createSecret: { type: 'corruption' }, who: 'target' }],
        tags: ['cruel'],
        hiddenEffects: true,
        ai: { base: 6, traits: { trusting: 20, cruel: 10, paranoid: -15 } },
      },
    ],
  },
  {
    id: 'council_ledger_investigation',
    category: 'council',
    title: 'Les preuves du clerc',
    text: 'Quelques mois de patience ont suffi. Votre clerc a reconstitué le chemin de l’argent : des marchés fictifs, des chevaux jamais livrés, une maison de pierre achetée au nom d’un cousin. {target.fullname} a détourné près de deux cents pièces d’or de votre trésor. Les preuves tiennent dans une cassette scellée, posée devant vous. Il ne reste qu’à décider de l’usage que vous en ferez.',
    illustration: 'council_chamber',
    trigger: 'chain',
    target: { pool: 'councillor' },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'imprison',
        label: '« Aux fers. Et que tout le royaume le sache. »',
        effects: [{ imprison: { by: 'root' }, who: 'target' }, { addAuthority: 20 }, { addGold: 80 }],
        ai: { base: 10, traits: { just: 20, wrathful: 10 }, personality: { honor: 10 } },
      },
      {
        id: 'restitution',
        label: '« Vous rendrez chaque pièce, et garderez votre siège, sous surveillance. »',
        effects: [{ addGold: 150 }, op('target', -20, 'forced_restitution')],
        tags: ['forgiving'],
        ai: { base: 10, traits: { greedy: 20 }, personality: { greed: 10 } },
      },
      {
        id: 'blackmail',
        label: '« Ces preuves resteront scellées. Tant que vous me servirez bien. »',
        effects: [
          { createSecret: { type: 'corruption', knownBy: ['root'] }, who: 'target' },
          { createHook: { on: 'target', strong: true, years: 20 } },
        ],
        tags: ['deceitful'],
        ai: { base: 6, traits: { deceitful: 15, honest: -20 }, personality: { intrigue: 15 } },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Vassaux
  // -------------------------------------------------------------------------
  {
    id: 'vassals_refuses_taxes',
    category: 'vassals',
    title: 'Le tribut retenu',
    text: 'Le collecteur envoyé chez {target.fullname} est revenu les mains vides et la mine basse. Selon lui, {target.title} a fait fermer ses portes et déclaré que les tributs de l’année resteraient dans ses coffres tant que la couronne ne lui aurait pas rendu la justice qu’elle lui doit. D’autres seigneurs, dit-on, observent l’affaire avec la plus grande attention.',
    illustration: 'castle_walls',
    trigger: 'pulse',
    weight: 10,
    target: { pool: 'vassal', where: { opinion: { max: 10 }, of: 'target', towards: 'root' } },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'send_men',
        label: '« Envoyez mes hommes d’armes. Le tribut, et les intérêts. »',
        effects: [{ addGold: 70 }, op('target', -30, 'tribute_seized'), { addVassalOpinion: -5, reason: 'heavy_handed' }],
        ai: { base: 10, traits: { wrathful: 15, greedy: 10 }, personality: { aggression: 10 } },
      },
      {
        id: 'hear_grievances',
        label: '« Écoutons donc ses griefs. »',
        effects: [{ addAuthority: -15 }, op('target', 15, 'grievances_heard')],
        tags: ['humble'],
        ai: { base: 10, traits: { patient: 15, humble: 10 }, personality: { compassion: 5, caution: 10 } },
      },
      {
        id: 'invoke_oath',
        label: '« Rappelez-lui son serment, devant ses pairs assemblés. »',
        cost: { prestige: 40 },
        effects: [{ addAuthority: 10 }, { addGold: 40 }, op('target', -10, 'oath_invoked')],
        ai: { base: 8, traits: { just: 15 }, personality: { honor: 10 } },
      },
    ],
  },
  {
    id: 'vassals_border_dispute',
    category: 'vassals',
    title: 'La borne déplacée',
    text: 'Une borne de pierre, plantée depuis trois générations entre les terres de {target.fullname} et celles de {other.fullname}, a été retrouvée cinquante pas plus loin, au beau milieu d’un pâturage convoité. Chacun accuse l’autre de l’avoir déplacée à la faveur de la nuit. Les deux seigneurs ont porté l’affaire devant vous et exigent un jugement, faute de quoi leurs gens régleront la question à coups de fourche.',
    illustration: 'fields',
    trigger: 'pulse',
    weight: 10,
    target: { pool: 'vassal' },
    other: { pool: 'vassal' },
    portraits: ['target', 'other'],
    choices: [
      {
        id: 'favor_target',
        label: '« La borne retournera là où {target.name} l’affirme. »',
        effects: [op('target', 20, 'won_arbitration'), op('other', -20, 'lost_arbitration')],
        ai: { base: 10 },
      },
      {
        id: 'favor_other',
        label: '« La borne retournera là où {other.name} l’affirme. »',
        effects: [op('other', 20, 'won_arbitration'), op('target', -20, 'lost_arbitration')],
        ai: { base: 10 },
      },
      {
        id: 'split',
        label: '« Le pâturage sera partagé, et la borne replantée au milieu. »',
        conditions: { skill: 'diplomacy', value: { min: 8 } },
        effects: [op('target', 5, 'fair_judgement'), op('other', 5, 'fair_judgement'), { addPrestige: 15 }],
        ai: { base: 12, traits: { just: 20, patient: 5 }, personality: { honor: 10 } },
      },
      {
        id: 'ignore',
        label: '« Qu’ils règlent eux-mêmes leurs querelles de bergers. »',
        effects: [{ addAuthority: -15 }, { createRelationship: { type: 'rival', with: 'other' }, who: 'target' }],
        ai: { base: 4, traits: { lazy: 20, content: 5 } },
      },
    ],
  },
  {
    id: 'vassals_charter_demand',
    category: 'vassals',
    title: 'La charte des seigneurs',
    text: 'Réunis derrière {target.fullname}, plusieurs de vos vassaux vous présentent un parchemin couvert de sceaux. Ils y réclament le droit d’être consultés avant toute levée extraordinaire, et la garantie qu’aucun d’eux ne sera jugé sans ses pairs. La démarche est courtoise, mais nul ne s’y trompe : ce qui n’est aujourd’hui qu’une supplique pourrait devenir demain une exigence, puis une révolte.',
    illustration: 'throne_room',
    trigger: 'pulse',
    weight: 7,
    cooldownDays: 3650,
    target: { pool: 'vassal' },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'seal_charter',
        label: '« Je scellerai cette charte. Mes vassaux ne sont pas mes ennemis. »',
        effects: [{ addAuthority: -40 }, { addVassalOpinion: 15, reason: 'charter_granted', months: 120 }],
        tags: ['humble'],
        ai: { base: 8, traits: { humble: 15, content: 10, ambitious: -15 }, personality: { ambition: -10 } },
      },
      {
        id: 'refuse',
        label: '« La couronne ne se partage pas. »',
        effects: [{ addAuthority: 15 }, { addVassalOpinion: -10, reason: 'charter_refused' }, op('target', -15, 'petition_rejected')],
        tags: ['ambitious'],
        ai: { base: 10, traits: { ambitious: 15, arrogant: 15 }, personality: { ambition: 10 } },
      },
      {
        id: 'negotiate',
        label: '« Discutons-en article par article. »',
        conditions: { skill: 'diplomacy', value: { min: 10 } },
        effects: [{ addAuthority: -10 }, { addVassalOpinion: 5, reason: 'charter_negotiated' }, { addStress: 10 }],
        ai: { base: 10, traits: { patient: 10, just: 5 } },
      },
      {
        id: 'buy_spokesman',
        label: '« Que {target.name} retire son nom de ce parchemin, et soit remercié{target.e}. »',
        cost: { gold: 100 },
        effects: [op('target', 20, 'bought_off'), { addVassalOpinion: -3, reason: 'charter_refused' }],
        tags: ['deceitful'],
        ai: { base: 6, traits: { deceitful: 10 }, personality: { intrigue: 10 } },
      },
    ],
  },
  {
    id: 'vassals_overmighty_murmurs',
    category: 'vassals',
    title: 'Un vassal trop puissant',
    text: 'Vos informateurs sont formels : {target.fullname} reçoit à sa table plus de chevaliers qu’il n’en faut pour garder ses terres, et ses festins résonnent de toasts où votre nom n’est jamais prononcé. Rien encore qui ressemble à une trahison. Mais l’on murmure dans les tavernes que la couronne pèserait mieux sur une autre tête, et ces murmures portent loin.',
    illustration: 'night_alley',
    trigger: 'pulse',
    weight: 8,
    cooldownDays: 3650,
    target: { pool: 'vassal', where: { opinion: { max: 15 }, of: 'target', towards: 'root' } },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'invite',
        label: '« Invitez {target.name} à ma cour, avec tous les honneurs. »',
        cost: { gold: 60 },
        effects: [op('target', 20, 'honoured_guest')],
        tags: ['social'],
        ai: { base: 10, traits: { sociable: 15, trusting: 10 }, personality: { caution: 5, sociability: 5 } },
      },
      {
        id: 'spy',
        label: '« Qu’on surveille ses allées et venues. »',
        tooltip: 'Vos espions rendront compte dans quelques mois.',
        effects: [{ triggerEvent: { id: 'vassals_overmighty_plot', days: 90 } }],
        ai: { base: 10, traits: { paranoid: 20 }, personality: { intrigue: 10 } },
      },
      {
        id: 'threaten',
        label: '« Rappelez-lui, par écrit, ce qu’il en coûte de défier la couronne. »',
        cost: { authority: 20 },
        effects: [op('target', -15, 'threatened'), { triggerEvent: { id: 'vassals_overmighty_defiance', days: 120 } }],
        ai: { base: 8, traits: { wrathful: 15, arrogant: 10 }, personality: { aggression: 15 } },
      },
      {
        id: 'ignore',
        label: '« Des bavardages d’ivrognes. »',
        effects: [{ addAuthority: -5 }, { chance: 40, then: [{ triggerEvent: { id: 'vassals_overmighty_defiance', days: 180 } }] }],
        hiddenEffects: true,
        ai: { base: 6, traits: { trusting: 20, lazy: 10, paranoid: -20 } },
      },
    ],
  },
  {
    id: 'vassals_overmighty_plot',
    category: 'vassals',
    title: 'Les lettres interceptées',
    text: 'Vos espions ont intercepté un courrier de {target.fullname}, adressé à plusieurs seigneurs du royaume. Le texte ne parle ni de révolte ni de trahison ; il évoque seulement l’heure où chacun devra choisir son camp, et propose une rencontre discrète après les moissons. C’est trop peu pour un procès. C’est assez pour ne plus jamais dormir tranquille.',
    illustration: 'night_alley',
    trigger: 'chain',
    target: { pool: 'vassal' },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'arrest',
        label: '« Qu’on s’en saisisse avant cette rencontre. »',
        cost: { authority: 40 },
        effects: [{ imprison: { by: 'root' }, who: 'target' }, { addVassalOpinion: -10, reason: 'arbitrary_arrest' }],
        ai: { base: 6, traits: { paranoid: 20, wrathful: 10 }, personality: { aggression: 10 } },
      },
      {
        id: 'buy_allies',
        label: '« Achetez ceux à qui ces lettres étaient destinées. »',
        cost: { gold: 100 },
        effects: [{ addVassalOpinion: 5, reason: 'royal_largesse' }, op('target', -10, 'plot_thwarted')],
        tags: ['generous'],
        ai: { base: 10, traits: { greedy: -15 }, personality: { intrigue: 10 } },
      },
      {
        id: 'keep_letters',
        label: '« Gardez ces lettres. Elles valent mieux qu’une armée. »',
        effects: [
          { createSecret: { type: 'political_crime', knownBy: ['root'] }, who: 'target' },
          { createHook: { on: 'target', years: 10 } },
        ],
        tags: ['deceitful'],
        ai: { base: 8, traits: { deceitful: 10, patient: 10 }, personality: { intrigue: 15 } },
      },
      {
        id: 'private_talk',
        label: '« Je lui montrerai moi-même ces lettres, en tête à tête. »',
        effects: [
          {
            chance: 50,
            then: [op('target', 15, 'spared_in_private'), { addAuthority: 10 }],
            else: [op('target', -20, 'confronted_in_private')],
          },
        ],
        tags: ['honest', 'brave'],
        ai: { base: 8, traits: { honest: 15, brave: 10 }, personality: { honor: 10 } },
      },
    ],
  },
  {
    id: 'vassals_overmighty_defiance',
    category: 'vassals',
    title: 'Le défi dans la grande salle',
    text: 'Devant toute votre cour assemblée, {target.fullname} a refusé de ployer le genou. Son regard ne vous a pas quitté tandis qu’un murmure parcourait la salle : les uns retenaient leur souffle, les autres cachaient mal leur sourire. Ce qui se passera dans les prochains instants sera raconté dans chaque château du royaume, et chacun jugera la couronne à l’aune de votre réponse.',
    illustration: 'throne_room',
    trigger: 'chain',
    major: true,
    target: { pool: 'vassal' },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'force_kneel',
        label: '« Gardes ! Aidez donc ce genou à se souvenir de son devoir. »',
        effects: [
          { addAuthority: 25 },
          { addPrestige: 30 },
          op('target', -40, 'humiliated_before_court'),
          { createRelationship: { type: 'rival', with: 'root' }, who: 'target' },
        ],
        tags: ['vengeful'],
        ai: { base: 8, traits: { wrathful: 20, arrogant: 15 }, personality: { aggression: 10 } },
      },
      {
        id: 'yield',
        label: '« Soit. Parlons plutôt de ce qui vous a offensé{target.e}. »',
        effects: [{ addAuthority: -30 }, { addPrestige: -40 }, op('target', 25, 'grievances_heard')],
        tags: ['humble'],
        ai: { base: 6, traits: { humble: 20, craven: 15 }, personality: { caution: 10 } },
      },
      {
        id: 'challenge',
        label: '« Si vous doutez de mon droit, prouvez-le l’épée à la main. »',
        conditions: { all: [{ age: { max: 55 } }, { skill: 'martial', value: { min: 8 } }] },
        effects: [
          {
            chance: 55,
            then: [{ addPrestige: 150 }, { addAuthority: 30 }, { woundCharacter: true, who: 'target' }],
            else: [{ woundCharacter: true }, { addPrestige: -60 }, { addAuthority: -20 }],
          },
        ],
        tags: ['brave'],
        ai: { base: 5, traits: { brave: 25, craven: -40 }, personality: { aggression: 15 } },
      },
      {
        id: 'mock',
        label: '« Le vin de nos caves vous monte vite aux genoux, semble-t-il. »',
        conditions: { skill: 'diplomacy', value: { min: 12 } },
        effects: [{ addPrestige: 60 }, op('target', -15, 'mocked_at_court')],
        ai: { base: 8, traits: { sociable: 10 }, personality: { sociability: 10 } },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Économie
  // -------------------------------------------------------------------------
  {
    id: 'economy_new_tax',
    category: 'economy',
    title: 'L’impôt des moulins',
    text: 'Votre intendant a passé la nuit sur ses comptes et vous en présente le fruit : une taxe nouvelle, prélevée sur chaque sac de grain moulu dans vos terres. Le calcul est séduisant, les coffres se rempliraient vite. Mais le grain est le pain du pauvre, et les seigneurs de vos provinces, qui possèdent eux aussi leurs moulins, n’accueilleront pas la mesure avec des chants de joie.',
    illustration: 'council_chamber',
    trigger: 'pulse',
    weight: 10,
    portraits: ['root'],
    choices: [
      {
        id: 'levy',
        label: '« Qu’on la proclame dès le prochain marché. »',
        effects: [
          { addModifier: { id: 'economy_mill_tax', months: 60, values: { tax_mult: 0.12 } } },
          { changeControl: -5 },
          { addVassalOpinion: -8, reason: 'mill_tax', months: 60 },
        ],
        tags: ['greedy'],
        ai: { base: 10, traits: { greedy: 20, ambitious: 10, compassionate: -10 }, personality: { greed: 15 } },
      },
      {
        id: 'crown_mills_only',
        label: '« Seuls les moulins de la couronne seront taxés. »',
        effects: [{ addModifier: { id: 'economy_crown_mill_tax', months: 60, values: { tax_mult: 0.05 } } }, { changeControl: -3 }],
        ai: { base: 12, personality: { caution: 10 } },
      },
      {
        id: 'reject',
        label: '« Le pain restera sans taxe. »',
        effects: [{ changeControl: 3 }, { addPrestige: 10 }],
        tags: ['compassionate', 'generous'],
        ai: { base: 8, traits: { compassionate: 15, generous: 10, greedy: -15 }, personality: { compassion: 10 } },
      },
    ],
  },
  {
    id: 'economy_merchant_guild',
    category: 'economy',
    title: 'La guilde des drapiers',
    text: 'Les maîtres drapiers de {province.name} se sont constitués en guilde et sollicitent une charte : monopole sur la teinture, droit de juger leurs propres apprentis et exemption du péage des ponts. En échange, ils promettent une ville plus riche, des marchés plus animés et un présent fort généreux le jour de la signature. Les petits artisans, eux, craignent d’être écrasés sous les métiers des puissants.',
    illustration: 'market',
    trigger: 'pulse',
    weight: 10,
    portraits: ['root'],
    choices: [
      {
        id: 'full_charter',
        label: '« Accordez la charte entière. »',
        effects: [
          { addGold: 60 },
          { addModifier: { id: 'economy_guild_charter', months: 120, values: { monthly_income_mult: 0.06 } } },
          { changeControl: -5 },
        ],
        ai: { base: 10, traits: { greedy: 15, ambitious: 10 }, personality: { greed: 10 } },
      },
      {
        id: 'limited_charter',
        label: '« Le monopole, oui ; la justice, non. »',
        effects: [{ addGold: 30 }, { addModifier: { id: 'economy_guild_charter', months: 120, values: { monthly_income_mult: 0.03 } } }],
        ai: { base: 12, traits: { just: 10, patient: 5 } },
      },
      {
        id: 'sell_charter',
        label: '« Leur charte a un prix. Qu’ils doublent leur présent. »',
        effects: [{ addGold: 150 }, { changeControl: -3 }],
        tags: ['greedy'],
        ai: { base: 8, traits: { greedy: 20 }, personality: { greed: 15 } },
      },
      {
        id: 'refuse',
        label: '« Mes artisans ne seront pas les valets de quelques drapiers. »',
        effects: [{ changeControl: 5 }, { addPrestige: 10 }],
        tags: ['compassionate'],
        ai: { base: 8, traits: { compassionate: 15, just: 10 }, personality: { compassion: 10 } },
      },
    ],
  },
  {
    id: 'economy_poor_harvest',
    category: 'economy',
    title: 'Le grain pourri sur pied',
    text: 'Des semaines de pluie ininterrompue ont noyé les champs autour de {province.name}. Le froment a germé dans l’épi, l’orge noircit en meule et les paysans ramènent des charrettes à moitié vides. Votre intendant estime les réserves à deux mois, trois tout au plus. Au-delà, il faudra choisir entre les greniers de la couronne et ceux des chaumières.',
    illustration: 'fields',
    trigger: 'pulse',
    weight: 9,
    cooldownDays: 2920,
    portraits: ['root'],
    choices: [
      {
        id: 'open_granaries',
        label: '« Ouvrez les greniers de la couronne. »',
        cost: { gold: 60 },
        effects: [{ changeDevelopment: -2 }, { changeControl: 3 }, { addPrestige: 20 }],
        tags: ['generous', 'compassionate'],
        ai: { base: 10, traits: { compassionate: 20, generous: 10, greedy: -10 }, personality: { compassion: 10 } },
      },
      {
        id: 'buy_grain',
        label: '« Achetez du grain aux marchands étrangers, à n’importe quel prix. »',
        cost: { gold: 120 },
        effects: [{ addPrestige: 30 }, { changeControl: 5 }],
        tags: ['generous'],
        ai: { base: 8, traits: { generous: 10, greedy: -20 }, personality: { compassion: 5, greed: -10 } },
      },
      {
        id: 'requisition',
        label: '« Les seigneurs partageront l’effort : réquisitionnez leurs réserves. »',
        effects: [{ addVassalOpinion: -10, reason: 'grain_requisition' }, { changeDevelopment: -3 }, { addAuthority: 10 }],
        ai: { base: 8, traits: { arbitrary: 15, ambitious: 10 }, personality: { aggression: 5 } },
      },
      {
        id: 'wait',
        label: '« Le ciel se lassera avant nous. Attendons. »',
        effects: [{ triggerEvent: { id: 'economy_famine_spreads', days: 90 } }],
        hiddenEffects: true,
        ai: { base: 8, traits: { greedy: 15, lazy: 15 }, personality: { greed: 10 } },
      },
    ],
  },
  {
    id: 'economy_famine_spreads',
    category: 'economy',
    title: 'La faim aux portes',
    text: 'La disette s’est changée en famine. Des familles entières quittent leurs villages pour camper au pied de vos murailles, et l’on a trouvé ce matin des enfants endormis pour toujours dans les fossés. Une fièvre commence à courir parmi les réfugiés. Vos capitaines demandent l’ordre de fermer les portes ; vos prêtres, celui de les ouvrir. Tous se tournent vers vous.',
    illustration: 'plague',
    trigger: 'chain',
    portraits: ['root'],
    choices: [
      {
        id: 'alms',
        label: '« Ouvrez les portes et distribuez le pain de ma table. »',
        tooltip: 'La fièvre des réfugiés pourrait franchir les murs.',
        cost: { gold: 100 },
        effects: [{ changeDevelopment: -4 }, { addFervor: 20 }, { addPrestige: 30 }, { chance: 15, then: [{ addTrait: 'ill' }] }],
        tags: ['compassionate', 'generous'],
        ai: { base: 10, traits: { compassionate: 25, generous: 15 }, personality: { compassion: 15 } },
      },
      {
        id: 'close_gates',
        label: '« Fermez les portes. Personne n’entre. »',
        effects: [
          { changeDevelopment: -8 },
          { changeLevies: -150 },
          { triggerEvent: { id: 'economy_famine_riots', days: 60 } },
        ],
        tags: ['cruel'],
        ai: { base: 8, traits: { cruel: 15, paranoid: 15, compassionate: -20 }, personality: { compassion: -10, caution: 10 } },
      },
      {
        id: 'procession',
        label: '« Que les prêtres mènent une procession dans chaque paroisse. »',
        cost: { fervor: 30 },
        effects: [
          {
            chance: 50,
            then: [{ changeDevelopment: -3 }],
            else: [{ changeDevelopment: -6 }, { triggerEvent: { id: 'economy_famine_riots', days: 60 } }],
          },
        ],
        tags: ['pious'],
        ai: { base: 8, traits: { zealous: 20, cynical: -10 }, personality: { zeal: 15 } },
      },
    ],
  },
  {
    id: 'economy_famine_riots',
    category: 'economy',
    title: 'L’émeute du pain',
    text: 'À l’aube, une foule affamée a forcé les portes de la halle aux grains et pillé l’entrepôt d’un marchand accusé d’accaparement. Le malheureux a été pendu à sa propre enseigne. Les émeutiers se sont retranchés dans le quartier des tanneurs, d’où ils réclament du pain, le pardon et la tête de votre intendant. La garde attend vos ordres, arbalètes chargées.',
    illustration: 'village',
    trigger: 'chain',
    major: true,
    portraits: ['root'],
    choices: [
      {
        id: 'crush',
        label: '« Que la garde fasse son office. »',
        effects: [{ changeControl: 10 }, { changeDevelopment: -4 }, { changeLevies: -100 }, { addAuthority: 10 }],
        tags: ['cruel'],
        ai: { base: 8, traits: { cruel: 20, wrathful: 15, compassionate: -20 }, personality: { aggression: 10 } },
      },
      {
        id: 'bread_and_pardon',
        label: '« Du pain, et le pardon pour ceux qui déposeront les armes. »',
        cost: { gold: 80 },
        effects: [{ changeControl: -5 }, { addAuthority: -10 }, { addPrestige: 15 }],
        tags: ['compassionate', 'forgiving'],
        ai: { base: 10, traits: { compassionate: 15, generous: 10 }, personality: { compassion: 10 } },
      },
      {
        id: 'hoarders',
        label: '« Livrez-leur les accapareurs. Tous, et leurs greniers avec. »',
        effects: [{ addGold: 60 }, { changeControl: 5 }, { addAuthority: -5 }],
        tags: ['cruel'],
        ai: { base: 8, traits: { greedy: 10, arbitrary: 10 }, personality: { intrigue: 10, greed: 10 } },
      },
    ],
  },
  {
    id: 'economy_bountiful_year',
    category: 'economy',
    title: 'L’année des greniers pleins',
    text: 'Jamais les anciens de {province.name} n’avaient vu pareille moisson. Les granges débordent, les charrettes encombrent les routes et le prix du pain est tombé si bas que les boulangers se plaignent. Votre intendant propose de tirer parti de cette abondance avant que l’hiver ou les rats ne la réduisent. Encore faut-il décider au profit de qui.',
    illustration: 'fields',
    trigger: 'pulse',
    weight: 9,
    portraits: ['root'],
    choices: [
      {
        id: 'sell',
        label: '« Vendez le surplus aux cités marchandes. »',
        effects: [{ addGold: 100 }],
        ai: { base: 10, traits: { greedy: 15 }, personality: { greed: 15 } },
      },
      {
        id: 'store',
        label: '« Remplissez les greniers de la couronne pour les années maigres. »',
        effects: [{ addModifier: { id: 'economy_full_granaries', months: 60, values: { development_growth: 0.03, control_growth: 0.1 } } }],
        ai: { base: 10, traits: { patient: 20, diligent: 5 }, personality: { caution: 15 } },
      },
      {
        id: 'festival',
        label: '« Qu’on célèbre la moisson dans chaque village ! »',
        cost: { gold: 40 },
        effects: [{ addPrestige: 50 }, { changeControl: 5 }, { addVassalOpinion: 5, reason: 'harvest_festival', months: 24 }],
        tags: ['generous', 'social'],
        ai: { base: 10, traits: { sociable: 20, generous: 10 }, personality: { sociability: 10 } },
      },
    ],
  },
  {
    id: 'economy_bandits',
    category: 'economy',
    title: 'Brigands sur la grande route',
    text: 'Une bande de brigands s’est établie dans les bois qui bordent la grande route de {province.name}. Ils ont détroussé trois convois ce mois-ci, pendu un sergent et laissé en vie un seul marchand, pour qu’il raconte l’histoire. Les caravaniers commencent à prendre d’autres chemins, et vos péages se vident à mesure. On dit leur chef ancien soldat, et fort habile.',
    illustration: 'forest',
    trigger: 'pulse',
    weight: 10,
    portraits: ['root'],
    choices: [
      {
        id: 'raise_levies',
        label: '« Levez les hommes du comté et battez les bois. »',
        effects: [{ changeLevies: -120 }, { changeControl: 8 }],
        tags: ['brave'],
        ai: { base: 10, traits: { brave: 10 }, personality: { aggression: 10 } },
      },
      {
        id: 'bounty_hunters',
        label: '« Engagez des chasseurs de primes. »',
        cost: { gold: 70 },
        effects: [{ changeControl: 6 }],
        ai: { base: 10, traits: { greedy: -10 }, personality: { caution: 5 } },
      },
      {
        id: 'pardon_recruit',
        label: '« Offrez-leur le pardon s’ils entrent à mon service. »',
        effects: [{ recruitMaa: { unit: 'archers', men: 100 } }, { addAuthority: -15 }, { changeControl: 3 }],
        tags: ['forgiving'],
        ai: { base: 6, traits: { cynical: 10 }, personality: { ambition: 10, intrigue: 5 } },
      },
      {
        id: 'ignore',
        label: '« Les marchands n’ont qu’à payer des escortes. »',
        effects: [{ changeControl: -8 }, { changeDevelopment: -3 }],
        ai: { base: 4, traits: { lazy: 20, greedy: 10 } },
      },
    ],
  },
  {
    id: 'economy_bridge_collapse',
    category: 'economy',
    title: 'Le pont emporté',
    text: 'La crue de printemps a emporté le vieux pont de pierre qui enjambait la rivière de {province.name}. Deux charrettes et leur attelage ont disparu avec lui. Désormais, marchands et pèlerins doivent faire un détour de trois jours ou se confier à des passeurs qui ont déjà triplé leurs prix. Votre maître d’œuvre attend vos instructions, ses plans roulés sous le bras.',
    illustration: 'village',
    trigger: 'pulse',
    weight: 8,
    portraits: ['root'],
    choices: [
      {
        id: 'stone_bridge',
        label: '« Un pont de pierre, plus large et plus haut que l’ancien. »',
        cost: { gold: 150 },
        effects: [{ changeDevelopment: 4 }, { addPrestige: 40 }],
        ai: { base: 8, traits: { ambitious: 15, diligent: 10, greedy: -15 } },
      },
      {
        id: 'wooden_bridge',
        label: '« Un pont de bois fera l’affaire, pour l’instant. »',
        cost: { gold: 50 },
        effects: [{ changeDevelopment: -1 }],
        ai: { base: 12, personality: { caution: 5 } },
      },
      {
        id: 'ferrymen',
        label: '« Affermez le passage aux passeurs, et prélevez votre part. »',
        effects: [{ addGold: 30 }, { changeDevelopment: -5 }, { changeControl: -2 }],
        tags: ['greedy'],
        ai: { base: 6, traits: { greedy: 20 }, personality: { greed: 10 } },
      },
    ],
  },
  {
    id: 'economy_mint_debasement',
    category: 'economy',
    title: 'L’argent coupé de cuivre',
    text: 'Votre maître de la monnaie vous soumet, à voix basse, une proposition qu’il n’oserait pas faire devant le conseil : fondre les pièces du trésor et les frapper à nouveau, avec un quart de cuivre en plus. Personne, assure-t-il, ne s’en apercevra avant des années. Les coffres gagneraient d’un coup ce que trois récoltes rapportent. Mais une monnaie trahie ne se relève pas aisément.',
    illustration: 'council_chamber',
    trigger: 'pulse',
    weight: 8,
    cooldownDays: 3650,
    portraits: ['root'],
    choices: [
      {
        id: 'debase',
        label: '« Faites fondre. Et que cela reste entre nous. »',
        effects: [
          { addGold: 180 },
          { addModifier: { id: 'economy_debased_coinage', months: 36, values: { monthly_income_mult: -0.06 } } },
          { chance: 40, then: [{ addVassalOpinion: -10, reason: 'debased_coin' }] },
        ],
        tags: ['deceitful', 'greedy'],
        ai: { base: 8, traits: { greedy: 20, deceitful: 15, honest: -20 }, personality: { greed: 15, honor: -10 } },
      },
      {
        id: 'light_debase',
        label: '« Un dixième de cuivre, pas davantage. »',
        effects: [{ addGold: 70 }, { addModifier: { id: 'economy_debased_coinage', months: 12, values: { monthly_income_mult: -0.02 } } }],
        tags: ['deceitful'],
        ai: { base: 10, personality: { greed: 5 } },
      },
      {
        id: 'refuse',
        label: '« La monnaie porte mon effigie. Elle ne mentira pas. »',
        effects: [{ addPrestige: 25 }],
        tags: ['honest'],
        ai: { base: 10, traits: { honest: 20, just: 10 }, personality: { honor: 10 } },
      },
    ],
  },
  {
    id: 'economy_peasant_unrest',
    category: 'economy',
    title: 'La grogne des corvées',
    text: 'Les paysans des hameaux voisins de {province.name} refusent de se présenter aux corvées du château. Ils étaient trois cents au printemps ; ils ne sont plus qu’une poignée, et les champs seigneuriaux restent en friche. Un vieux laboureur a porté leur plainte jusqu’à vos portes : trop de jours de travail, trop peu de pain, et un bailli qui se paie sur la bête.',
    illustration: 'village',
    trigger: 'pulse',
    weight: 10,
    conditions: { domainControl: { max: 85 } },
    portraits: ['root'],
    choices: [
      {
        id: 'reduce',
        label: '« Réduisez les corvées d’un tiers, et remplacez ce bailli. »',
        effects: [{ changeControl: 6 }, { changeDevelopment: 2 }, { addAuthority: -10 }],
        tags: ['compassionate'],
        ai: { base: 10, traits: { compassionate: 20, just: 10 }, personality: { compassion: 10 } },
      },
      {
        id: 'hang_leaders',
        label: '« Pendez les meneurs. Les autres reviendront. »',
        effects: [{ changeControl: 8 }, { changeDevelopment: -4 }, { addAuthority: 10 }],
        tags: ['cruel'],
        ai: { base: 8, traits: { cruel: 20, wrathful: 10, compassionate: -20 }, personality: { compassion: -10 } },
      },
      {
        id: 'speak_to_villages',
        label: '« Je parlerai moi-même aux villages. »',
        conditions: { skill: 'diplomacy', value: { min: 10 } },
        effects: [{ changeControl: 5 }, { addPrestige: 25 }, { addStress: 10 }],
        tags: ['social', 'humble'],
        ai: { base: 10, traits: { sociable: 15, humble: 10, reclusive: -15 }, personality: { sociability: 10 } },
      },
      {
        id: 'bailiff_repays',
        label: '« Le bailli restera. Mais qu’il rende ce qu’il a volé. »',
        effects: [{ addGold: 40 }, { changeControl: 3 }],
        ai: { base: 10, traits: { just: 15, greedy: 5 } },
      },
    ],
  },
  {
    id: 'economy_building_inauguration',
    category: 'economy',
    title: 'Le dernier coup de marteau',
    text: 'Les travaux s’achèvent enfin à {province.name}. Les maçons ont retiré leurs échafaudages, les charpentiers ont planté un rameau vert au sommet de l’ouvrage, selon l’usage, et tout le bourg s’est rassemblé pour contempler ce que l’or de votre trésor a fait naître. Le maître d’œuvre, chapeau bas, attend de savoir comment vous souhaitez marquer ce jour.',
    illustration: 'village',
    trigger: 'on:building_complete',
    weight: 10,
    cooldownDays: 1095,
    portraits: ['root'],
    choices: [
      {
        id: 'workers_feast',
        label: '« Un banquet pour les ouvriers et leurs familles. »',
        cost: { gold: 30 },
        effects: [{ changeControl: 5 }, { addPrestige: 20 }],
        tags: ['generous', 'social'],
        ai: { base: 10, traits: { sociable: 15, generous: 10 } },
      },
      {
        id: 'blessing',
        label: '« Que les prêtres bénissent l’ouvrage. »',
        effects: [{ addFervor: 20 }, { changeDevelopment: 1 }],
        tags: ['pious'],
        ai: { base: 10, traits: { zealous: 15 }, personality: { zeal: 10 } },
      },
      {
        id: 'inscription',
        label: '« Qu’on grave mon nom au fronton, en lettres d’or. »',
        cost: { gold: 20 },
        effects: [{ addPrestige: 45 }, { changeControl: -2 }],
        tags: ['ambitious'],
        ai: { base: 8, traits: { arrogant: 20, ambitious: 10, humble: -15 } },
      },
      {
        id: 'back_to_work',
        label: '« Il reste tant à bâtir. Au travail. »',
        effects: [{ addAuthority: 5 }, { changeDevelopment: 1 }],
        tags: ['humble'],
        ai: { base: 8, traits: { diligent: 20, humble: 5 } },
      },
    ],
  },
  {
    id: 'economy_construction_accident',
    category: 'economy',
    title: 'Le prix des pierres',
    text: 'À la veille de l’achèvement des travaux de {province.name}, un échafaudage a cédé sous le poids d’un bloc mal arrimé. Quatre ouvriers ont péri, dont le fils du maître maçon. L’ouvrage est debout, mais le chantier a changé de couleur : les compagnons portent le deuil, parlent de mauvais présage et laissent entendre que la faute revient aux économies faites sur le bois des échafauds.',
    illustration: 'village',
    trigger: 'on:building_complete',
    weight: 5,
    cooldownDays: 1825,
    portraits: ['root'],
    choices: [
      {
        id: 'compensate',
        label: '« Les familles seront indemnisées par la couronne. »',
        cost: { gold: 50 },
        effects: [{ changeControl: 4 }, { addStress: -5 }],
        tags: ['compassionate', 'generous'],
        ai: { base: 10, traits: { compassionate: 20, greedy: -15 }, personality: { compassion: 10 } },
      },
      {
        id: 'blame_foreman',
        label: '« Le contremaître répondra de sa négligence. »',
        effects: [{ addAuthority: 10 }, { changeControl: -2 }],
        ai: { base: 10, traits: { just: 10, arbitrary: 5 } },
      },
      {
        id: 'memorial',
        label: '« Leurs noms seront gravés à la porte, et un office dit chaque année. »',
        cost: { gold: 20 },
        effects: [{ addFervor: 15 }, { addPrestige: 10 }],
        tags: ['pious'],
        ai: { base: 10, traits: { zealous: 15 }, personality: { zeal: 10 } },
      },
      {
        id: 'harsh_words',
        label: '« Les chantiers tuent. C’est le métier de ceux qui y travaillent. »',
        effects: [{ changeControl: -5 }],
        tags: ['cruel'],
        ai: { base: 5, traits: { cruel: 15, greedy: 10, compassionate: -20 } },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Culture
  // -------------------------------------------------------------------------
  {
    id: 'culture_market_brawl',
    category: 'culture',
    title: 'Deux peuples, un marché',
    text: 'Une rixe a éclaté au grand marché de {province.name} entre des marchands venus des terres de {target.fullname} et des gens de votre propre peuple. Chacun parlait sa langue, chacun a compris l’autre de travers : il y a eu des étals renversés, deux morts et beaucoup d’insultes. Chaque camp réclame désormais justice, et {target.fullname} vous a écrit en termes glacés.',
    illustration: 'market',
    trigger: 'pulse',
    weight: 10,
    target: { pool: 'vassal', where: { not: { sameCulture: 'root', who: 'target' } } },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'own_people',
        label: '« Mon peuple a été provoqué. Les étrangers paieront l’amende. »',
        effects: [{ addPrestige: 20 }, { changeControl: 3 }, op('target', -25, 'partial_judgement')],
        ai: { base: 8, traits: { arrogant: 15, arbitrary: 10, just: -10 } },
      },
      {
        id: 'protect_foreigners',
        label: '« Ceux qui commercent sous ma protection y restent, d’où qu’ils viennent. »',
        effects: [op('target', 20, 'protected_kinsfolk'), { changeControl: -4 }],
        tags: ['compassionate'],
        ai: { base: 8, traits: { compassionate: 10, just: 10 }, personality: { compassion: 10 } },
      },
      {
        id: 'one_law',
        label: '« Une même loi pour tous : les coupables des deux camps seront punis. »',
        cost: { authority: 20 },
        effects: [op('target', 10, 'fair_judgement'), { changeControl: 2 }, { addPrestige: 15 }],
        tags: ['honest'],
        ai: { base: 10, traits: { just: 20, honest: 5 }, personality: { honor: 10 } },
      },
    ],
  },
  {
    id: 'culture_house_chronicle',
    category: 'culture',
    title: 'La chronique de votre maison',
    text: 'Un vieux moine lettré, réputé pour la beauté de sa main, propose de consacrer ses dernières années à rédiger la chronique de votre maison. Il réclame l’accès à vos archives, des vélins en quantité et la liberté d’écrire ce qu’il y trouvera. Or certaines pages de votre lignée, vous le savez, gagneraient à rester dans l’ombre des coffres.',
    illustration: 'library',
    trigger: 'pulse',
    weight: 8,
    cooldownDays: 5475,
    portraits: ['root'],
    choices: [
      {
        id: 'whole_truth',
        label: '« Écrivez tout. La vérité honore mieux qu’un mensonge doré. »',
        cost: { gold: 60 },
        effects: [{ addRenown: 30 }, { addPrestige: 40 }],
        tags: ['honest'],
        ai: { base: 10, traits: { honest: 20, just: 10, deceitful: -15 }, personality: { honor: 10 } },
      },
      {
        id: 'flattering',
        label: '« Écrivez ce qui mérite d’être retenu. Je vous dirai quoi. »',
        tooltip: 'Les moines ont la mémoire longue et la langue parfois déliée.',
        cost: { gold: 60 },
        effects: [{ addPrestige: 80 }, { chance: 25, then: [{ addPrestige: -60 }] }],
        tags: ['deceitful', 'ambitious'],
        ai: { base: 8, traits: { deceitful: 15, arrogant: 15, honest: -20 }, personality: { ambition: 10 } },
      },
      {
        id: 'refuse',
        label: '« Le passé de ma maison ne regarde que ma maison. »',
        effects: [{ addPrestige: -10 }],
        tags: ['reclusive'],
        ai: { base: 8, traits: { reclusive: 20, paranoid: 10, greedy: 10 } },
      },
    ],
  },
  {
    id: 'culture_court_tongue',
    category: 'culture',
    title: 'La langue de la cour',
    text: 'Depuis quelques saisons, les jeunes gens de votre cour délaissent la langue de leurs pères pour un parler étranger, jugé plus raffiné : on y chante l’amour, on y rédige les billets galants, on s’y moque des vieilles tournures. Les anciens s’en offusquent et votre chapelain y voit le signe d’un déclin. Votre intendant, plus pragmatique, note que les marchands étrangers s’en réjouissent.',
    illustration: 'garden',
    trigger: 'pulse',
    weight: 8,
    cooldownDays: 3650,
    portraits: ['root'],
    choices: [
      {
        id: 'embrace',
        label: '« Que l’on parle comme on voudra, pourvu qu’on parle bien. »',
        effects: [
          { addModifier: { id: 'culture_cosmopolitan_court', months: 60, values: { diplomacy: 1, monthly_income_mult: 0.03 } } },
          { addVassalOpinion: -5, reason: 'foreign_airs', months: 36 },
        ],
        ai: { base: 10, traits: { sociable: 15, cynical: 10 }, personality: { sociability: 10 } },
      },
      {
        id: 'ancestral_tongue',
        label: '« À ma table, on parlera la langue de mes ancêtres. »',
        effects: [{ addPrestige: 15 }, { addVassalOpinion: 5, reason: 'ancestral_customs', months: 36 }],
        ai: { base: 10, traits: { arrogant: 10, zealous: 10 }, personality: { zeal: 5 } },
      },
      {
        id: 'native_letters',
        label: '« Faisons plutôt fleurir notre propre poésie. »',
        cost: { gold: 50 },
        effects: [{ addPrestige: 30 }, { addModifier: { id: 'culture_native_letters', months: 60, values: { monthly_prestige: 0.3 } } }],
        tags: ['generous'],
        ai: { base: 8, traits: { generous: 10, diligent: 5, greedy: -10 } },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Religion
  // -------------------------------------------------------------------------
  {
    id: 'religion_preacher_capital',
    category: 'religion',
    title: 'Le prêcheur des marches',
    text: 'Un prêcheur aux pieds nus harangue chaque soir les foules sur les marches du grand temple de {province.name}. Il accuse les prêtres de vendre la grâce au poids de l’or et affirme que la lumière divine parle directement au cœur des humbles, sans passer par les autels. Les pauvres l’écoutent avec ferveur ; le haut clergé exige que vous fassiez taire cette voix avant qu’elle ne devienne un chœur.',
    illustration: 'chapel',
    trigger: 'pulse',
    weight: 9,
    cooldownDays: 3650,
    portraits: ['root'],
    choices: [
      {
        id: 'arrest',
        label: '« Qu’on l’arrête pour trouble à l’ordre public. »',
        effects: [{ addFervor: 25 }, { changeControl: -3 }],
        tags: ['pious'],
        ai: { base: 10, traits: { zealous: 20, cynical: -10 }, personality: { zeal: 10 } },
      },
      {
        id: 'let_him_speak',
        label: '« Laissez-le parler. Les mots ne blessent que les coupables. »',
        tooltip: 'Une parole libre ne s’arrête pas aux marches d’un temple.',
        effects: [{ addFervor: -15 }, { changeControl: 3 }, { triggerEvent: { id: 'religion_heresy_spreads', days: 120 } }],
        tags: ['impious'],
        ai: { base: 8, traits: { cynical: 20, compassionate: 5, zealous: -20 }, personality: { zeal: -10 } },
      },
      {
        id: 'public_debate',
        label: '« Je le confronterai moi-même, devant le peuple. »',
        conditions: { skill: 'learning', value: { min: 10 } },
        effects: [
          {
            chance: 60,
            then: [{ addFervor: 30 }, { addPrestige: 40 }],
            else: [{ addPrestige: -30 }, { triggerEvent: { id: 'religion_heresy_spreads', days: 90 } }],
          },
        ],
        tags: ['brave'],
        ai: { base: 8, traits: { arrogant: 10, brave: 5 }, personality: { zeal: 10, sociability: 5 } },
      },
      {
        id: 'escort_out',
        label: '« Qu’on le reconduise aux frontières, avec du pain pour la route. »',
        effects: [{ addFervor: 10 }, { chance: 30, then: [{ triggerEvent: { id: 'religion_heresy_spreads', days: 150 } }] }],
        tags: ['compassionate'],
        hiddenEffects: true,
        ai: { base: 10, traits: { compassionate: 10, patient: 5 }, personality: { caution: 10 } },
      },
    ],
  },
  {
    id: 'religion_heresy_spreads',
    category: 'religion',
    title: 'Les lampes éteintes',
    text: 'Le prêcheur a quitté {province.name}, mais sa parole est restée. Dans les faubourgs, on se réunit la nuit autour de lampes éteintes pour prier sans prêtres, et l’on refuse désormais la dîme. Plus troublant encore : vos gens ont vu {target.fullname} sortir de l’une de ces assemblées, au petit matin. Le haut clergé réclame des bûchers ; vos percepteurs, des dîmes. Vous seul décidez jusqu’où ira le feu.',
    illustration: 'night_alley',
    trigger: 'chain',
    target: { pool: 'courtier' },
    portraits: ['root', 'target'],
    choices: [
      {
        id: 'purge',
        label: '« Arrêtez les meneurs, {target.name} compris{target.e}. »',
        effects: [
          { imprison: { by: 'root' }, who: 'target' },
          { addTrait: 'heretic', who: 'target' },
          { addFervor: 30 },
          { changeControl: -5 },
        ],
        tags: ['pious', 'cruel'],
        ai: { base: 8, traits: { zealous: 25, cruel: 10, compassionate: -15 }, personality: { zeal: 15 } },
      },
      {
        id: 'quiet_warning',
        label: '« Avertissez {target.name} en privé. Pour les autres, doublez les gardes. »',
        effects: [
          { createSecret: { type: 'heresy', knownBy: ['root'] }, who: 'target' },
          { createHook: { on: 'target', years: 10 } },
          { addFervor: -10 },
          { changeControl: -2 },
          { triggerEvent: { id: 'religion_heresy_schism', days: 180 } },
        ],
        ai: { base: 10, traits: { patient: 10 }, personality: { intrigue: 10 } },
      },
      {
        id: 'tolerate',
        label: '« Qu’ils prient comme ils l’entendent, s’ils paient leurs impôts. »',
        effects: [
          { addFervor: -30 },
          { changeControl: 3 },
          op('target', 20, 'tolerated_worship'),
          { triggerEvent: { id: 'religion_heresy_schism', days: 150 } },
        ],
        tags: ['impious'],
        ai: { base: 8, traits: { cynical: 20, zealous: -25 }, personality: { zeal: -15 } },
      },
      {
        id: 'attend',
        label: '« Et s’ils avaient raison ? Menez-moi à leur prochaine assemblée. »',
        conditions: { not: { hasTrait: 'zealous' } },
        tooltip: 'Si cela venait à se savoir, le clergé ne vous le pardonnerait pas.',
        effects: [
          { createSecret: { type: 'heresy', knownBy: ['target'] } },
          { addFervor: -20 },
          { addStress: -10 },
          { addMutualOpinion: { with: 'target', value: 25, reason: 'shared_prayers' } },
        ],
        tags: ['impious'],
        ai: { base: 2, traits: { cynical: 10, mystic: 10 }, personality: { zeal: -5 } },
      },
    ],
  },
  {
    id: 'religion_heresy_schism',
    category: 'religion',
    title: 'L’ultimatum du clergé',
    text: 'Le mouvement des lampes éteintes compte désormais des fidèles dans chaque paroisse de {province.name}, et plusieurs prêtres ont quitté leur autel pour le rejoindre. Le haut clergé vous adresse une lettre solennelle : si la couronne ne condamne pas publiquement l’hérésie avant la prochaine fête sainte, il fera prêcher contre vous dans tous les temples du royaume. Le temps des demi-mesures est passé.',
    illustration: 'chapel',
    trigger: 'chain',
    major: true,
    portraits: ['root'],
    choices: [
      {
        id: 'condemn',
        label: '« Je condamnerai l’hérésie, du haut des marches du temple. »',
        effects: [
          { addFervor: 50 },
          { changeControl: -8 },
          { changeDevelopment: -3 },
          { addVassalOpinion: 5, reason: 'defender_of_faith', months: 36 },
        ],
        tags: ['pious'],
        ai: { base: 10, traits: { zealous: 25, cynical: -10 }, personality: { zeal: 15 } },
      },
      {
        id: 'defy_clergy',
        label: '« La couronne ne prend pas ses ordres chez les prêtres. »',
        effects: [
          { addFervor: -60 },
          { addAuthority: 20 },
          { changeControl: 5 },
          { addVassalOpinion: -10, reason: 'defied_clergy', months: 60 },
        ],
        tags: ['impious', 'ambitious'],
        ai: { base: 6, traits: { cynical: 20, ambitious: 10, arrogant: 10, zealous: -30 }, personality: { zeal: -15 } },
      },
      {
        id: 'council_of_faith',
        label: '« Réunissons un concile : que les deux partis débattent devant moi. »',
        conditions: { any: [{ skill: 'diplomacy', value: { min: 12 } }, { skill: 'learning', value: { min: 12 } }] },
        cost: { gold: 100 },
        effects: [{ addFervor: 10 }, { addPrestige: 30 }, { changeControl: -2 }],
        ai: { base: 10, traits: { patient: 15, just: 10 }, personality: { caution: 10 } },
      },
    ],
  },
  {
    id: 'religion_miracle_claim',
    category: 'religion',
    title: 'La source de la bergère',
    text: 'Une jeune bergère des collines affirme qu’une source a jailli sous ses pas au lendemain d’une vision, et que son eau guérit les fièvres. Déjà, des malades affluent par centaines, les aubergistes doublent leurs prix et un prêtre du lieu parle de bâtir une chapelle. Les docteurs de votre foi, prudents, attendent que la couronne se prononce avant de s’engager.',
    illustration: 'fields',
    trigger: 'pulse',
    weight: 9,
    portraits: ['root'],
    choices: [
      {
        id: 'endorse',
        label: '« Un miracle, sur mes terres ! Qu’on bâtisse la chapelle. »',
        tooltip: 'Si la supercherie venait à être révélée…',
        cost: { gold: 50 },
        effects: [{ addFervor: 40 }, { addPrestige: 20 }, { chance: 25, then: [{ addPrestige: -50 }] }],
        tags: ['pious'],
        ai: { base: 10, traits: { zealous: 20, trusting: 15, cynical: -15 }, personality: { zeal: 10 } },
      },
      {
        id: 'examine',
        label: '« Que des savants examinent cette eau avant toute chose. »',
        cost: { gold: 20 },
        effects: [{ chance: 50, then: [{ addFervor: 25 }], else: [{ addFervor: -10 }, { addAuthority: 5 }] }],
        ai: { base: 10, traits: { diligent: 10, cynical: 5 }, personality: { caution: 10 } },
      },
      {
        id: 'tax_pilgrims',
        label: '« Miracle ou non, taxons les pèlerins. »',
        effects: [{ addGold: 80 }, { addFervor: -20 }],
        tags: ['greedy', 'impious'],
        ai: { base: 6, traits: { greedy: 20, zealous: -20 }, personality: { greed: 15 } },
      },
      {
        id: 'forbid',
        label: '« Que la bergère retourne à ses moutons. Il n’y a pas de miracle. »',
        effects: [{ addFervor: -15 }, { addAuthority: 10 }],
        tags: ['impious'],
        ai: { base: 6, traits: { cynical: 20, zealous: -20 } },
      },
    ],
  },
  {
    id: 'religion_pilgrimage',
    category: 'religion',
    title: 'Le chemin des sept autels',
    text: 'Votre confesseur vous presse depuis des mois d’entreprendre le pèlerinage des sept autels, qui serpente à travers les montagnes jusqu’au plus ancien sanctuaire de votre foi. Le voyage est long, les cols dangereux, et le royaume devra se passer de vous toute une saison. Mais ceux qui en reviennent, dit-on, en reviennent changés, et nul ne met plus jamais en doute leur piété.',
    illustration: 'mountains',
    trigger: 'pulse',
    weight: 8,
    cooldownDays: 3650,
    conditions: { all: [{ isAdult: true }, { atWar: false }, { age: { max: 65 } }] },
    portraits: ['root'],
    choices: [
      {
        id: 'go',
        label: '« Préparez mon bâton et mon manteau de pèlerin. »',
        tooltip: 'Les cols de montagne ne font pas de différence entre les rois et les mendiants.',
        cost: { gold: 60 },
        effects: [
          { addFervor: 60 },
          { addStress: -30 },
          { addPrestige: 30 },
          { addAuthority: -15 },
          { chance: 15, then: [{ woundCharacter: true }] },
        ],
        tags: ['pious', 'humble'],
        ai: { base: 8, traits: { zealous: 25, humble: 10, cynical: -15 }, personality: { zeal: 15 } },
      },
      {
        id: 'send_offering',
        label: '« Qu’on porte au sanctuaire une offrande en mon nom. »',
        cost: { gold: 50 },
        effects: [{ addFervor: 20 }],
        ai: { base: 12, traits: { greedy: -10 } },
      },
      {
        id: 'refuse',
        label: '« Le royaume ne peut se passer de moi. »',
        effects: [{ addFervor: -10 }, { addAuthority: 5 }],
        ai: { base: 8, traits: { diligent: 10, cynical: 15, zealous: -15 } },
      },
    ],
  },
  {
    id: 'religion_holy_festival',
    category: 'religion',
    title: 'La fête des premières lueurs',
    text: 'La grande fête sainte approche, et le prévôt du temple de {province.name} vient vous soumettre ses préparatifs. Selon l’usage, le seigneur du lieu offre les cierges, le banquet des pauvres et les présents aux prêtres. Les années fastes, on a vu des processions de mille flambeaux ; les années maigres, un simple office à l’aube. Le prévôt attend de savoir quel genre d’année sera celle-ci.',
    illustration: 'chapel',
    trigger: 'pulse',
    weight: 10,
    portraits: ['root'],
    choices: [
      {
        id: 'lavish',
        label: '« Mille flambeaux, et qu’on en parle jusqu’aux frontières. »',
        cost: { gold: 90 },
        effects: [{ addFervor: 35 }, { addPrestige: 40 }, { addVassalOpinion: 5, reason: 'grand_festival', months: 24 }],
        tags: ['pious', 'generous'],
        ai: { base: 8, traits: { zealous: 15, generous: 15, sociable: 10, greedy: -15 } },
      },
      {
        id: 'modest',
        label: '« Faites ce qui convient, sans excès. »',
        cost: { gold: 25 },
        effects: [{ addFervor: 10 }],
        ai: { base: 14 },
      },
      {
        id: 'skip',
        label: '« Un office à l’aube suffira bien. »',
        effects: [{ addFervor: -20 }, { changeControl: -2 }],
        tags: ['greedy', 'impious'],
        ai: { base: 6, traits: { greedy: 20, cynical: 15 } },
      },
    ],
  },
  {
    id: 'religion_relic_for_sale',
    category: 'religion',
    title: 'L’os du saint',
    text: 'Un marchand à l’accent chantant vous présente, dans un coffret d’ivoire doublé de soie, ce qu’il affirme être un os de la main de l’un des premiers saints de votre foi, arraché, avoue-t-il sans honte, à un sanctuaire en ruine d’outre-mer. Il en demande une petite fortune. Vos prêtres se disputent déjà à voix basse : relique inestimable, ou vulgaire os de chèvre ?',
    illustration: 'chapel',
    trigger: 'pulse',
    weight: 8,
    cooldownDays: 3650,
    portraits: ['root'],
    choices: [
      {
        id: 'buy',
        label: '« Payez-le. Une telle relique n’a pas de prix. »',
        cost: { gold: 150 },
        effects: [{ addFervor: 40 }, HOLY_RELIC],
        tags: ['pious'],
        ai: { base: 8, traits: { zealous: 20, trusting: 10, greedy: -20 }, personality: { zeal: 10 } },
      },
      {
        id: 'haggle',
        label: '« La moitié, ou remportez votre os de chèvre. »',
        effects: [{ chance: 50, then: [{ addGold: -75 }, { addFervor: 20 }, HOLY_RELIC], else: [{ addPrestige: -15 }] }],
        tags: ['greedy'],
        ai: { base: 8, traits: { greedy: 15 }, personality: { greed: 10 } },
      },
      {
        id: 'examine',
        label: '« Laissez-moi examiner cet os de près. »',
        conditions: { skill: 'learning', value: { min: 12 } },
        effects: [{ addFervor: 10 }, { addPrestige: 25 }],
        ai: { base: 10, traits: { diligent: 10, cynical: 10 } },
      },
      {
        id: 'refuse',
        label: '« On ne marchande pas le sacré. Qu’il quitte ma cour. »',
        effects: [{ addFervor: 10 }],
        tags: ['pious', 'honest'],
        ai: { base: 10, traits: { honest: 10 } },
      },
    ],
  },
];

/** Libellés des raisons d'opinion et modificateurs introduits par ces événements. */
export const LOC_COURT: Record<string, string> = {
  // Raisons d'opinion
  'opinion.reason.spared_humiliation': 'Humiliation épargnée',
  'opinion.reason.public_humiliation': 'Humilié en public',
  'opinion.reason.lavish_host': 'Hôte fastueux',
  'opinion.reason.granted_satisfaction': 'Duel accordé',
  'opinion.reason.denied_satisfaction': 'Réparation refusée',
  'opinion.reason.forced_reconciliation': 'Réconciliation imposée',
  'opinion.reason.grand_joust': 'Grande joute',
  'opinion.reason.fine_tutor': 'Précepteur de renom',
  'opinion.reason.reprimanded': 'Réprimandé',
  'opinion.reason.forgiven_blunder': 'Erreur pardonnée',
  'opinion.reason.fiscal_reforms': 'Réformes fiscales',
  'opinion.reason.counsel_heeded': 'Conseil suivi',
  'opinion.reason.counsel_ignored': 'Conseil ignoré',
  'opinion.reason.rewarded_service': 'Services récompensés',
  'opinion.reason.honoured_at_court': 'Honoré à la cour',
  'opinion.reason.refused_honours': 'Honneurs refusés',
  'opinion.reason.vague_promise': 'Vague promesse',
  'opinion.reason.backed_in_council': 'Soutenu au conseil',
  'opinion.reason.overruled_in_council': 'Désavoué au conseil',
  'opinion.reason.accused_of_theft': 'Accusé de vol',
  'opinion.reason.falsely_accused': 'Accusé à tort',
  'opinion.reason.defended_honour': 'Honneur défendu',
  'opinion.reason.forced_restitution': 'Restitution forcée',
  'opinion.reason.tribute_seized': 'Tribut saisi',
  'opinion.reason.heavy_handed': 'Main de fer',
  'opinion.reason.grievances_heard': 'Griefs entendus',
  'opinion.reason.oath_invoked': 'Serment rappelé',
  'opinion.reason.won_arbitration': 'Arbitrage favorable',
  'opinion.reason.lost_arbitration': 'Arbitrage défavorable',
  'opinion.reason.fair_judgement': 'Jugement équitable',
  'opinion.reason.charter_granted': 'Charte accordée',
  'opinion.reason.charter_refused': 'Charte refusée',
  'opinion.reason.charter_negotiated': 'Charte négociée',
  'opinion.reason.petition_rejected': 'Supplique rejetée',
  'opinion.reason.bought_off': 'Acheté',
  'opinion.reason.honoured_guest': 'Hôte honoré',
  'opinion.reason.threatened': 'Menacé',
  'opinion.reason.arbitrary_arrest': 'Arrestation arbitraire',
  'opinion.reason.royal_largesse': 'Largesses royales',
  'opinion.reason.plot_thwarted': 'Menées déjouées',
  'opinion.reason.spared_in_private': 'Épargné en privé',
  'opinion.reason.confronted_in_private': 'Confronté en privé',
  'opinion.reason.humiliated_before_court': 'Humilié devant la cour',
  'opinion.reason.mocked_at_court': 'Raillé à la cour',
  'opinion.reason.mill_tax': 'Impôt des moulins',
  'opinion.reason.grain_requisition': 'Réquisition de grain',
  'opinion.reason.harvest_festival': 'Fête des moissons',
  'opinion.reason.debased_coin': 'Monnaie altérée',
  'opinion.reason.partial_judgement': 'Jugement partial',
  'opinion.reason.protected_kinsfolk': 'Protection des siens',
  'opinion.reason.foreign_airs': 'Manières étrangères',
  'opinion.reason.ancestral_customs': 'Coutumes ancestrales',
  'opinion.reason.tolerated_worship': 'Culte toléré',
  'opinion.reason.shared_prayers': 'Prières partagées',
  'opinion.reason.defender_of_faith': 'Défenseur de la foi',
  'opinion.reason.defied_clergy': 'Clergé défié',
  'opinion.reason.grand_festival': 'Grande fête sainte',
  // Modificateurs
  'modifier.court_patron_of_letters': 'Protecteur des lettres',
  'modifier.council_fiscal_reforms': 'Réformes fiscales',
  'modifier.economy_mill_tax': 'Impôt des moulins',
  'modifier.economy_crown_mill_tax': 'Taxe des moulins royaux',
  'modifier.economy_guild_charter': 'Charte des drapiers',
  'modifier.economy_full_granaries': 'Greniers pleins',
  'modifier.economy_debased_coinage': 'Monnaie altérée',
  'modifier.culture_cosmopolitan_court': 'Cour cosmopolite',
  'modifier.culture_native_letters': 'Lettres ancestrales',
  'modifier.religion_holy_relic': 'Sainte relique',
};
