/** Codes d'erreur stables partagés entre serveur, simulation et client. */
export const ErrorCodes = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL: 'INTERNAL',
  PROTOCOL_MISMATCH: 'PROTOCOL_MISMATCH',

  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  GAME_NOT_STARTED: 'GAME_NOT_STARTED',
  GAME_FULL: 'GAME_FULL',
  GAME_OVER: 'GAME_OVER',
  NOT_GAME_MEMBER: 'NOT_GAME_MEMBER',
  NOT_HOST: 'NOT_HOST',
  INVALID_INVITE: 'INVALID_INVITE',
  CHARACTER_TAKEN: 'CHARACTER_TAKEN',
  CHARACTER_NOT_PLAYABLE: 'CHARACTER_NOT_PLAYABLE',
  PLAYERS_NOT_READY: 'PLAYERS_NOT_READY',
  SAVE_INCOMPATIBLE: 'SAVE_INCOMPATIBLE',

  INVALID_COMMAND: 'INVALID_COMMAND',
  DUPLICATE_COMMAND: 'DUPLICATE_COMMAND',
  STALE_GAME_VERSION: 'STALE_GAME_VERSION',
  NOT_YOUR_CHARACTER: 'NOT_YOUR_CHARACTER',
  INSUFFICIENT_GOLD: 'INSUFFICIENT_GOLD',
  INSUFFICIENT_PRESTIGE: 'INSUFFICIENT_PRESTIGE',
  INSUFFICIENT_AUTHORITY: 'INSUFFICIENT_AUTHORITY',
  INSUFFICIENT_FERVOR: 'INSUFFICIENT_FERVOR',
  INVALID_TARGET: 'INVALID_TARGET',
  NO_VALID_CLAIM: 'NO_VALID_CLAIM',
  ALREADY_AT_WAR: 'ALREADY_AT_WAR',
  NOT_AT_WAR: 'NOT_AT_WAR',
  ARMY_NOT_OWNED: 'ARMY_NOT_OWNED',
  ARMY_BUSY: 'ARMY_BUSY',
  NO_PATH: 'NO_PATH',
  PROVINCE_NOT_OWNED: 'PROVINCE_NOT_OWNED',
  BUILDING_UNAVAILABLE: 'BUILDING_UNAVAILABLE',
  CONSTRUCTION_IN_PROGRESS: 'CONSTRUCTION_IN_PROGRESS',
  ALREADY_MARRIED: 'ALREADY_MARRIED',
  PROPOSAL_REJECTED: 'PROPOSAL_REJECTED',
  ON_COOLDOWN: 'ON_COOLDOWN',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  CHOICE_UNAVAILABLE: 'CHOICE_UNAVAILABLE',
  TITLE_NOT_HELD: 'TITLE_NOT_HELD',
  REQUIREMENTS_NOT_MET: 'REQUIREMENTS_NOT_MET',
  CHARACTER_DEAD: 'CHARACTER_DEAD',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/** Erreur métier levée par la simulation ou le serveur. */
export class GameError extends Error {
  readonly code: ErrorCode;
  readonly details: Record<string, unknown> | undefined;

  constructor(code: ErrorCode, message?: string, details?: Record<string, unknown>) {
    super(message ?? code);
    this.name = 'GameError';
    this.code = code;
    this.details = details;
  }
}

export function isGameError(err: unknown): err is GameError {
  return err instanceof GameError;
}
